// Ayarlar (İngilizce)
import type { ayarlar as tr } from "../tr/ayarlar";

export const ayarlar: typeof tr = {
  baslik: "Settings",
  aciklama: "Core settings apply to every project",
  alinamadi: "Couldn't load settings.",
  kaydedildi: "Settings saved.",
  degisiklikYok: "No changes",
  dil: {
    aciklama: "The interface and the agents use this language. Running agents switch at their next session.",
  },
  claude: {
    baslik: "Claude Code",
  },
  github: {
    baslik: "GitHub",
  },
  projeKoku: {
    baslik: "Project folder",
    aciklama: "New projects and repositories cloned from GitHub are created in this folder.",
    varsayilanEtiket: "default",
    degistir: "Change",
    varsayilan: "Use default",
    secBaslik: "Choose the project folder",
    kaydedildi: (yol: string) => `New projects will be created in ${yol}.`,
  },
  kurulum: {
    baslik: "First-run setup",
    aciklama: "Shows the language, Claude Code, GitHub, first project and kickoff steps again. Your settings and projects stay as they are.",
    ac: "Reopen the setup wizard",
  },
  giris: {
    baslik: "Subscription and limits",
    kaynak: "sign-in",
    ulasilamadi: (hata: string) => `Couldn't reach Claude Code: ${hata}`,
    okunmadi: "Claude Code sign-in hasn't been read yet.",
    sifirlanma: (zaman: string) => `resets ${zaman}`,
    yenidenOku: "Read sign-in again",
    abonelik:
      "ArnOrg runs only on a Claude subscription: agents use your Claude Code sign-in on this machine (Pro, Max or Team). Your plan's 5-hour and weekly windows count; an API key in the environment is never passed to agents.",
    besSaat: "5-hour window cap (%)",
    besSaatIpucu: "Agents stop at this percentage; the rest is left for you. 0 means no cap.",
    hafta: "Weekly window cap (%)",
    haftaIpucu: "When the window resets, agents pick up where they left off.",
  },
  calismaDuzeni: {
    baslik: "Work rules",
    esZamanli: "Agents working at once (ceiling)",
    esZamanliIpucu:
      "The most agents doing work at the same time, across all projects. In a fully autonomous project the CEO sets the team pace under this ceiling; in board mode this ceiling applies. The project's usage level limits it too (Normal 6, Economy 3). When it's full, new work waits in line and starts as a slot opens. 0 means no limit.",
    esZamanliHata: "Must be a whole number from 0 to 50.",
    tavan: "Task token ceiling (millions)",
    tavanIpucu: "On the Normal level, when a task has used this many tokens its agent stops and asks for approval to go on; approving raises the ceiling by the same amount again. Smart doubles it and Economy halves it. 0 turns it off.",
    tavanHata: "Must be between 0 and 1000.",
    surdur: "Resume unfinished work on launch",
    surdurIpucu: "When ArnOrg reopens, agents that were working when it closed pick up where they left off, in the same conversation. Agents stopped with Stop work stay stopped.",
  },
  cekirdek: {
    baslik: "Core",
    claudeYolu: "Claude Code path",
    claudeYoluOrnek: "Empty: PATH first, then the binary bundled with the SDK",
    ghYolu: "GitHub CLI (gh) path",
    ghYoluOrnek: "Empty: PATH first, then the copy ArnOrg downloaded",
    izinModu: "Default permission mode",
    izinModuIpucu: "Whatever the mode, every call passes through the PreToolUse gate.",
    sure: "Decision timeout (seconds)",
    sureHata: "At least 10 seconds.",
    sureIpucu: "When time runs out, the pending tool call is rejected.",
    saklama: "Keep audit records (days)",
    saklamaHata: "Must be a whole number from 0 to 3650.",
    saklamaIpucu: "Older records move to monthly JSONL files in the data folder's arsiv directory. 0 keeps them forever.",
    tikanma: "Stall threshold (minutes)",
    tikanmaHata: "Must be between 0 and 1440.",
    tikanmaIpucu: "If a task makes no progress for this long, its owner gets a reminder; then it goes to their manager and the Board. 0 turns it off.",
    editor: "External editor",
    editorBaska: "Another command…",
    editorKomutu: "Editor command",
  },
  kodZekasi: {
    baslik: "Code intel",
    model: "Semantic search model",
    modeller: { kaliteli: "Quality", hizli: "Fast", kapali: "Off" },
    kapaliIpucu: "Code is searched by keyword and symbol name only; no model is downloaded.",
    modelIpucu: "The model downloads on first use and runs on this machine; your code never leaves it.",
    indirildi: (mb: number) => `Downloaded (${mb} MB).`,
    indirilecek: (mb: number) => `Downloads ~${mb} MB on first use.`,
    yerel: "The model runs on this machine; your code never leaves it.",
    otomatik: "Index projects automatically",
    otomatikIpucu:
      "When on, the main repo is indexed in the background when ArnOrg starts and when a project is added; changed files update on their own. When off, the first search starts indexing.",
  },
  sistem: {
    baslik: "System",
    bulundu: "Found",
    bulunamadi: "Not found",
    yol: "Path",
    veriDizini: "Data directory",
    uyari: "Agents can't start. Install Claude Code or set its path above.",
  },
  tarayici: {
    baslik: "This browser",
    sirketAdi: "Company name shown in the top bar",
    uygula: "Apply",
    yerel: "Stored only in this browser.",
    sirketGuncellendi: "Company name updated.",
    baglanti: "Connection",
    anahtariUnut: "Forget key",
    baglantiyiKes: "Disconnect this tab",
    anahtarIpucu: "The access key is kept in sessionStorage; once it's forgotten, you'll need to paste it again.",
  },
  hakkinda: {
    baslik: "About",
  },
};
