// 0.0.10 · Usage level (Smart, Normal, Economy) and the project token budget: opening a project, Project settings,
// the budget indicator and panel in the top bar, spending in Headquarters, task tokens on the Board, the level in an
// employee's model
export const butce = {
  seviye: {
    baslik: "Usage level",
    adlar: { zeki: "Smart", normal: "Normal", tasarruflu: "Economy" },
    aciklamalar: {
      zeki: "The strongest models and deep thinking; for hard work. Uses up the subscription fastest.",
      normal: "Power and spend in balance; for most projects.",
      tasarruflu: "Light models and short thinking; for simple work and tight budgets.",
    },
    kademeler: { yonetim: "CEO, CTO, code review", gelistirme: "Development", destek: "Testing, docs, promotion" },
    derinlik: { high: "deep thinking", medium: "medium thinking", low: "short thinking" },
    tavan: (t: string) => `task ceiling ${t}`,
    tavanKapali: "task ceiling off",
    tempo: (n: number) => `at most ${n} ${n === 1 ? "employee" : "employees"} at once`,
    tempoSinirsiz: "no limit on employees at once",
    degisti: (ad: string) => `The usage level is now ${ad}.`,
  },
  butce: {
    baslik: "Token budget",
    toplam: "Total budget",
    gunluk: "Daily budget",
    birim: "million tokens",
    sinirsiz: "Unlimited",
    milyon: (m: number) => `${m}M`,
    hazirEtiket: (ad: string) => `${ad}: presets`,
    toplamIpucu: "All of the project's usage. When it runs out the team stops; raise it and the team picks up where it left off.",
    gunlukIpucu: "Renews every midnight. When it runs out the team stops until the next day.",
    hata: "Enter a number (e.g. 20 or 2.5); leave it empty for unlimited.",
    harcanan: (toplam: string, bugun: string) => `${toplam} tokens used so far; ${bugun} today.`,
    kaydet: "Save budget",
    kaydedildi: "Budget saved.",
  },
  kademe: {
    etiket: "Automatic step-down",
    ipucu: "When 80% of the budget or of the weekly subscription window is used, the level steps down one notch and steps back up once that clears. At 80% of the budget you and the CEO are warned.",
    acildi: "Automatic step-down is on.",
    kapandi: "Automatic step-down is off.",
  },
  acilis: {
    baslik: "Usage and budget",
    aciklama: "The level sets the employees' models and thinking depth; the budget caps the tokens the project can spend. You can change both later in Project settings or from the top bar.",
  },
  ayar: {
    baslik: "Usage and budget",
    kademede: (etkin: string, secilen: string, neden: string) => `Running on ${etkin} for now (${neden}); it goes back to ${secilen} once that clears.`,
    nedenler: {
      butce: "80% of the budget is used",
      pencere: (ad: string) => `subscription window: ${ad} is past 80%`,
    },
    elleNotu: "A model you chose for an employee by hand stays as it is; pick “Follow the level” in the employee's model to tie it to the level again.",
  },
  gosterge: {
    butce: "Budget",
    bugun: "Today",
    toplam: "Total",
    birim: "tokens",
    seviyeEtiketi: (ad: string) => `Level: ${ad}`,
    baslik: (parcalar: string[]) => `${parcalar.join(" · ")}. Click for details and the budget.`,
    kalem: (ad: string, harcanan: string, sinir: string, yuzde: string) => `${ad} ${harcanan} / ${sinir} (${yuzde})`,
    toplamKalem: (toplam: string) => `${toplam} tokens in total`,
    seviyeKalem: (ad: string) => `level ${ad}`,
    doldu: "budget used up, the team is stopped",
  },
  panel: {
    baslik: "Usage and budget",
    kapat: "Close the panel",
    seviye: "Level",
    gecerli: (etkin: string, neden: string) => `Now ${etkin} (${neden})`,
    toplam: "Total",
    gunluk: "Today",
    butceYok: "No budget: the project spends without a limit.",
    harcandi: (t: string) => `${t} tokens used`,
    tahmin: (sure: string, an: string) => `At this pace it runs out in about ${sure} (${an}).`,
    tahminYok: "Not enough usage in the last hour to estimate when it runs out.",
    sure: {
      gun: (n: number) => (n === 1 ? "1 day" : `${n} days`),
      saat: (n: number) => `${n} h`,
      dakika: (n: number) => `${n} min`,
    },
    doldu: { toplam: "The project budget is used up; the team is stopped. Raise the budget and it picks up where it left off.", gunluk: "Today's budget is used up; the team is stopped until midnight. Raise the budget and it carries on right away." },
    uyari: (yuzde: string) => `${yuzde} of the budget is used.`,
    artir: "Raise the budget",
    butceKoy: "Set a budget",
    adim: (m: string) => `Make it ${m}`,
    vazgec: "Cancel",
    kaydet: "Save",
    artirildi: "Budget updated.",
    pahali: "Most expensive tasks",
    tumu: "Spending in Headquarters",
  },
  harcama: {
    baslik: "Spending",
    gorevler: "Most expensive tasks",
    gorevlerBos: "No tokens have been counted against tasks yet; tokens an employee uses while working on a task count toward that task.",
    calisanlar: "Per employee (so far)",
    calisanlarBos: "No tokens used yet.",
    atanmadi: "unassigned",
    tavan: (tavan: string) => `ceiling ${tavan}`,
    gorevAc: (kod: string) => `Open ${kod} on the Board`,
  },
  gorev: {
    tokenBaslik: (tam: string, tavan: string | null) => `Tokens used on this task: ${tam}${tavan ? ` · task ceiling ${tavan}` : ""}`,
    harcanan: "Tokens used",
    tavanli: (t: string, tavan: string) => `${t} / ${tavan} (task ceiling)`,
  },
  model: {
    seviyeyeGore: (model: string) => `Follow the level · ${model}`,
    seviyeyeGoreKisa: "follows the level",
    sabit: "chosen by hand",
    baglandi: (ad: string, model: string) => `${ad} now follows the level (${model}).`,
  },
  bildirim: {
    artir: "Raise the budget",
  },
};
