// Denetim ve politika (İngilizce)
import type { denetim as tr } from "../tr/denetim";

export const denetim: typeof tr = {
  baslik: "Audit",
  altBaslik: "Every tool call goes through ArnOrg's gate · policy in .arnorg/proje.yaml",
  bekleyenler: "Calls awaiting a decision",
  bekliyor: (n: number) => `${n} pending`,
  bekleyenYokKisa: "none",
  bekleyenYok: 'No calls are waiting for your decision. Calls caught by an "Ask for approval" rule show up here; if time runs out, the call is denied.',
  sonKararlar: "Recent decisions",
  kapi: "PreToolUse gate",
  karaGore: "Filter by decision",
  ajanaGore: "Filter by agent",
  butunAjanlar: "All agents",
  araEtiket: "Search records",
  araYer: "Search: command, path, rule",
  eslesenYok: "No matching records",
  eslesenYokMetin: "Loosen the filters.",
  henuzYok: "No records yet",
  henuzYokMetin: "Once agents start working, every tool call and the decision on it is listed here.",
  sutun: {
    saat: "Time",
    ajan: "Agent",
    arac: "Tool",
    girdi: "Input",
    karar: "Decision",
    kural: "Rule",
  },
  dahaGoster: (n: number) => `Show ${n} more`,
  politika: "Policy",
  politikaAlt: "allow · deny · ask for approval",

  cagri: {
    ajan: "Agent",
    bilinmeyenAjan: "Unknown agent",
    etiket: (ajan: string) => `Call from ${ajan} awaiting a decision`,
    karar: (ajan: string, arac: string, izin: boolean) => `${ajan} · ${arac}: ${izin ? "allowed" : "denied"}.`,
    doldu: "Time's up · will be denied",
    kaldi: (sure: string) => `${sure} left`,
    kural: (kural: string) => `Rule: ${kural}`,
    notEtiketi: "Decision note (optional)",
    notYer: "Note (optional) · e.g. Push your branch and open a PR",
    izinVer: "Allow",
    reddet: "Deny",
  },

  kural: {
    hedefler: {
      komut: "Shell command",
      yol: "File path",
      url: "Address (URL)",
      arac: "Tool name",
    },
    yeniKural: "New rule",
    alinamadi: "Couldn't load the policy.",
    kaydedildi: "Policy saved. New calls are checked against these rules.",
    yokBaslik: "No rules",
    yokMetin: "Without rules, every tool call is allowed. Add at least one deny rule for destructive commands.",
    anahtar: (ad: string, etkin: boolean) => `Rule ${ad} ${etkin ? "on" : "off"}`,
    desenYok: " · no patterns",
    karari: (ad: string) => `Decision for ${ad}`,
    ad: "Name",
    hedef: "Target",
    aciklama: "Description",
    desenler: "Patterns (one regular expression per line, case-insensitive)",
    araclar: "Tools (comma-separated; empty means every tool that fits the target)",
    yukari: "Move up",
    asagi: "Move down",
    sil: "Delete rule",
    ekle: "Add rule",
    kaydedilmemis: "Unsaved changes",
    kaydet: "Save policy",
    kaydedilemedi: "Couldn't save the policy",
    ipucu: "Rules are tried top to bottom; the first match decides. The policy lives in the repo in .arnorg/proje.yaml.",
  },
};
