// Ekip, organizasyon şeması, işe alım, ajan ayrıntısı ve eylemleri (İngilizce)
import type { ekip as tr } from "../tr/ekip";

export const ekip: typeof tr = {
  baslik: "Team",
  altBaslik: "Org chart · the CEO proposes hires, you approve them",
  iseAl: "Hire",
  alinamadi: "Couldn't load the team.",
  bosBaslik: "No one here yet",
  ilkCalisan: "Hire your first employee",
  bosMetin:
    "Every project starts with a CEO, hired automatically. Once the CEO has the brief, it proposes the roles it needs; you can also hire directly.",
  durumRenkleri: "Status colors",
  teklifler: "Hiring proposals",
  bekliyor: (n: number) => `${n} pending`,
  ayrintilari: (ad: string) => `${ad} details`,

  iseAlim: {
    rollerAlinamadi: "Couldn't load roles.",
    rollerYukleniyor: "Loading roles…",
    adGerekli: "Name is required.",
    adVar: "There's already an employee with this name.",
    alindi: (ad: string) => `${ad} is hired. Setting up their workspace.`,
    tekliflerOnaylarda: "The CEO's proposals land in Approvals",
    ad: "Name",
    adOrnek: "Alex",
    rol: "Role",
    model: "Model",
    rolOnerisi: " · suggested for the role",
    yonetici: "Manager",
    karakter: "Character",
    talimat: "Extra instructions (optional)",
    talimatOrnek: "Added to the role's instructions. E.g. Run an OWASP review before the payment integration.",
    alinamadiBaslik: "Couldn't hire",
  },

  ayrinti: {
    oturumuAc: "Open session",
    bugun: "Today",
    toplam: "Total",
    token: (miktar: string) => (miktar === "1" ? "1 token" : `${miktar} tokens`),
    izinModu: "Permission mode",
    yonetici: "Manager",
    gorev: "Task",
    dal: "Branch",
    calismaAlani: "Workspace",
    iseAlindi: "Hired",
    mesajGonder: "Send a message",
    ayarlar: "Settings",
    model: "Model",
    ozelModelSecenegi: "Custom model ID…",
    ozelModel: "Custom model ID",
    uygula: "Apply",
    modelDegisti: (ad: string, model: string) => `${ad} now runs on ${model}.`,
    ayarlarKaydedildi: "Agent settings saved.",
    plandanCikIpucu: "Goes back to the previous permission mode",
    planaAlIpucu: "The agent only writes a plan and doesn't change files",
    plandanCik: "Exit plan mode",
    planaAl: "Switch to plan mode",
    ekTalimat: "Extra instructions",
    ekTalimatOrnek: "Added to the role's instructions. E.g. Always write tests with vitest.",
    degisiklikleriKaydet: "Save changes",
    ofisKarakteri: "Office character",
    istenCikar: "Let go",
    istenCikarEvet: (ad: string) => `Yes, let ${ad} go`,
    istenCikarUyari: (ad: string) =>
      `If ${ad} is let go, their session closes. The identity file (.arnorg/ekip/) and the workspace stay where they are; their assigned tasks become unassigned.`,
    istenCikarildi: (ad: string) => `${ad} was let go. Their identity file and workspace stay in the repo.`,
  },

  eylem: {
    baslat: "Start",
    devamEttir: "Resume",
    kes: "Interrupt",
    kesIpucu: "Stops the running turn; the session stays open",
    durdur: "Stop",
    durdurIpucu: "Closes the session; the session ID is kept",
    turKesildi: (ad: string) => `${ad}'s turn was interrupted.`,
    oturumKapatildi: (ad: string) => `${ad}'s session was closed.`,
    basladi: (ad: string) => `${ad} started.`,
    ilkTalimat: "First instruction (optional)",
    ilkTalimatIpucu: "If left empty, it's generated from the assigned task",
    gorev: "Task",
    secilmedi: "None",
    ajaniBaslat: (ad: string) => `Start ${ad}`,
    mesajEtiketi: (ad: string) => `Message to ${ad}`,
    mesajYer: (ad: string, kapali: boolean) => `Write to ${ad}${kapali ? " · starts the session if it's off" : ""}`,
    mesajIletildi: (ad: string) => `Message delivered to ${ad}.`,
    turKesildiMesajIletildi: (ad: string) => `${ad}'s turn was interrupted; message delivered.`,
    hemen: "Now",
    hemenAciklama: "(interrupts the turn)",
    hemenIpucu: "Interrupts the running turn and delivers the message right away",
    enterIpucu: "Enter sends · Shift+Enter for a new line",
  },
};
