// Message attachments (English)
import type { ekler as tr } from "../tr/ekler";

export const ekler: typeof tr = {
  ekle: "Attach a file",
  ekleIpucu: "Attach an image, a PDF or a text file; you can also paste an image or drag files in",
  ipucu: "paste an image or drag files in",
  birak: "Drop to attach",
  birakAlt: (mb) => `Images, PDFs, text and code · up to ${mb} MB per file`,
  ciplerEtiketi: "Attachments to send",
  kaldir: (ad) => `Remove ${ad}`,
  yenidenDene: (ad) => `Upload ${ad} again`,
  yukleniyor: "Uploading",
  yuklemeOrani: (ad, yuzde) => `Uploading ${ad}: ${yuzde}%`,
  yuklenemedi: "Upload failed",
  cokBuyuk: (mb) => `Larger than ${mb} MB`,
  bos: "The file is empty",
  enCok: (n) => `A message can have at most ${n} attachments.`,
  bekliyor: "You can send once the attachments are uploaded",
  hataliVar: "Remove the attachment that failed, or try it again",
  yapistirilan: "screenshot",

  etiket: "Attachments",
  gorselAc: (ad) => `Enlarge ${ad}`,
  gorselAlinamadi: "Couldn't load the image",
  yenidenAl: "Try again",
  dahaFazla: (n) => `+${n}`,
  dahaFazlaEtiket: (n) => (n === 1 ? "1 more image" : `${n} more images`),
  ac: "Open",
  acIpucu: (ad) => `Open ${ad} in a new tab`,
  indir: "Download",
  indirIpucu: (ad) => `Download ${ad}`,
  kaydet: "Save",
  kaydetIpucu: (ad) => `Save ${ad}`,
  acilamadi: "Couldn't open the file.",
  turler: { gorsel: "Image", pdf: "PDF", metin: "Text", kod: "Code", veri: "Data" },
  ozet: (ad, kalan) => (kalan > 0 ? `${ad} +${kalan}` : ad),
  ekSayisi: (n) => (n === 1 ? "1 attachment" : `${n} attachments`),

  isik: {
    etiket: (ad) => `Image: ${ad}`,
    kapat: "Close (Esc)",
    onceki: "Previous image (←)",
    sonraki: "Next image (→)",
    sira: (i, n) => `${i} of ${n}`,
    gercekBoyut: "Actual size",
    sigdir: "Fit to screen",
    indir: "Download",
  },
};
