// Ortak sözcükler ve durum adları (İngilizce)
import { AD_HARITALARI_EN } from "@arnorg/ortak";
import type { genel as tr } from "../tr/genel";

export const genel: typeof tr = {
  kaydet: "Save",
  kaydedildi: "Saved.",
  vazgec: "Cancel",
  kapat: "Close",
  sil: "Delete",
  duzenle: "Edit",
  ekle: "Add",
  ara: "Search",
  yenile: "Refresh",
  yenidenDene: "Try again",
  yukleniyor: "Loading…",
  tamam: "OK",
  evet: "Yes",
  hayir: "No",
  onayla: "Approve",
  reddet: "Reject",
  gonder: "Send",
  ac: "Open",
  geri: "Back",
  ileri: "Next",
  devam: "Continue",
  bitir: "Finish",
  atla: "Skip",
  kopyala: "Copy",
  kopyalandi: "Copied",
  tumu: "All",
  yok: "None",
  henuzYok: "Not yet",
  bilinmiyor: "Unknown",
  hata: "Error",
  bilinmeyenHata: "Unknown error",
  kurul: "Board",
  arnorg: "ArnOrg",
  dil: "Language",
  ajanDurumu: AD_HARITALARI_EN.ajanDurumu,
  gorevDurumu: AD_HARITALARI_EN.gorevDurumu,
  karar: AD_HARITALARI_EN.karar,
  onayTuru: AD_HARITALARI_EN.onayTuru,
  hafizaTuru: AD_HARITALARI_EN.hafizaTuru,
  izinModu: {
    default: "Default",
    acceptEdits: "Accept edits",
    bypassPermissions: "Full access (through the gate)",
    plan: "Plan mode",
    dontAsk: "Don't ask",
    auto: "Auto",
  },
  calisanSayisi: (n: number) => `${n} ${n === 1 ? "employee" : "employees"}`,
  gorevSayisi: (n: number) => `${n} ${n === 1 ? "task" : "tasks"}`,
  kayitSayisi: (n: number) => `${n} ${n === 1 ? "record" : "records"}`,
};
