// Menü, üst çubuk, canlı ray, bildirimler ve uygulama kabuğu (İngilizce)
import type { gezinti as tr } from "../tr/gezinti";

export const gezinti: typeof tr = {
  menuEtiketi: "Studio menu",
  menu: {
    karargah: "Headquarters",
    ofis: "Office",
    ekip: "Team",
    pano: "Board",
    kanallar: "Channels",
    notlar: "Notes",
    hafiza: "Memory",
    kod: "Code",
    "kod-zekasi": "Code intel",
    zeka: "Intelligence",
    denetim: "Audit",
    onaylar: "Approvals",
    projeler: "Projects",
    ayarlar: "Settings",
  },
  onceProjeAc: "Open a project first",
  rozetArac: (n: number) => `${n} tool ${n === 1 ? "call awaits" : "calls await"} your decision`,
  rozetOnay: (n: number) => `${n} ${n === 1 ? "approval" : "approvals"} pending`,
  rozetSoru: (n: number) => `${n} ${n === 1 ? "question awaits" : "questions await"} an answer`,
  rozetOkunmamis: (n: number) => `${n} unread ${n === 1 ? "message" : "messages"}`,
  kodYukleniyor: "Loading the Code screen",
  kodZekasiYukleniyor: "Loading Code intel",
  bildirimKapat: "Dismiss notification",
  ust: {
    proje: "Project",
    projeSecin: "Choose a project",
    aktifBaslik: "Agents working or awaiting a decision",
    aktif: "active",
    calisan: (n: number) => (n === 1 ? "employee" : "employees"),
    ws: { bagli: "Live", baglaniyor: "Connecting", kopuk: "Offline" },
    wsBaslik: "Live event connection",
    wsKopukBaslik: "Live connection lost; retrying in the background. Click to retry now.",
    projeYok: "No projects yet.",
    tumProjeler: "All projects",
    yeniProje: "New project",
    mesai: "Stop work",
    mesaiBaslik: "Close every agent session in this project",
    acikOturumYok: "No open sessions",
    hepsiniDurdur: "Stop all",
    mesaiOnay: (n: number) =>
      `${n === 1 ? "1 agent session" : `${n} agent sessions`} will close. Running turns are interrupted; session IDs are kept, so agents can pick up where they left off later.`,
    mesaiDurdu: (n: number) => `Closed ${n === 1 ? "1 agent session" : `${n} agent sessions`}. Work stopped.`,
  },
  ray: {
    baslik: "Live feed",
    alt: "tool calls",
    goster: "Show live feed",
    gizle: "Hide live feed",
    gizleKisa: "Hide",
    bos: "Once agents start working, every tool call and audit decision streams in here.",
    onay: { bekliyor: "Needs approval", onaylandi: "Approved", reddedildi: "Rejected", zaman_asimi: "Timed out" },
    karar: { izin: "allowed", ret: "denied", sor: "needs approval", degisti: "input changed" },
    gorev: "task",
    hafiza: "memory",
    hafizaGuncel: "memory updated",
    soru: "question",
    yanit: "answer",
    yanitsiz: "unanswered",
  },
};
