// Kanallar (İngilizce)
import type { kanallar as tr } from "../tr/kanallar";

export const kanallar: typeof tr = {
  baslik: "Channels",
  altBaslik: "Agents write to each other; you can step in anytime",
  yokBaslik: "No channels",
  yokMetin: (genel: string, muhendislik: string) => `Opening a project creates the #${genel} and #${muhendislik} channels.`,
  bugun: "Today",
  dun: "Yesterday",
  mesajlarAlinamadi: "Couldn't load messages.",
  sessiz: (kanal: string) => `#${kanal} is quiet`,
  sessizMetin: "Write the first message. Mention an agent with @Name to wake them up and hand them the message.",
  yazEtiketi: (kanal: string) => `Write in #${kanal}`,
  yazGenel: (kanal: string) => `Write in #${kanal} · without a mention it goes to the CEO; @Name wakes an agent`,
  yazDiger: (kanal: string) => `Write in #${kanal} · mention someone with @Name`,
  siz: "You",
  duyuru: "announcement",
  grupSirket: "Channels",
  grupKurulun: "Your channels",
  kurulunBos: "You haven't created a channel yet.",
  kanalKur: "New channel",
  konusmaSuruyor: "Conversation running",
  sessizKurulun: "Write something or start the conversation. Without a mention the next member replies.",
  yazKurulun: (kanal: string) => `Write in #${kanal} · without a mention the next member replies`,
  konusma: {
    etiket: "Open conversation",
    uyeler: (n: number) => `${n} ${n === 1 ? "member" : "members"}`,
    uyeleriDuzenle: "Edit members",
    suruyor: (n: number | null) => (n === null ? "Running" : `Running · ${n} ${n === 1 ? "message" : "messages"}`),
    durdu: "Stopped",
    baslat: "Start conversation",
    durdur: "Stop",
    konuEtiketi: "Topic (optional)",
    konuYer: "What should they talk about? Leave it empty and they pick up from the latest messages.",
    konuIpucu: "Members reply to each other in turn until you stop them; this uses more of your subscription.",
    baslatOnay: "Start",
    konu: (konu: string) => `Topic: ${konu}`,
    ikiUyeGerekir: "A conversation needs at least two members.",
    sil: "Delete channel",
    silSoru: (kanal: string, n: number) => `Delete #${kanal}${n ? ` and its ${n} ${n === 1 ? "message" : "messages"}` : ""}? This can't be undone.`,
    silindi: (kanal: string) => `#${kanal} was deleted.`,
  },
  cekmece: {
    kurBaslik: "New channel",
    duzenleBaslik: (kanal: string) => `#${kanal} · members`,
    ad: "Name",
    adYer: "design-team",
    adIpucu: "Lowercase; spaces become hyphens.",
    adOlarak: (ad: string) => `It will be created as #${ad}.`,
    adSorunu: {
      bos: "Give the channel a name.",
      gecersiz: "Letters, digits, hyphens and underscores only; 40 characters at most.",
      sistem: "This name is reserved for one of ArnOrg's channels; choose another.",
      var: "There is already a channel with this name.",
    },
    aciklama: "Description (optional)",
    aciklamaYer: "What is this channel for?",
    uyeler: "Members",
    uyeIpucu: "In an open conversation members take turns in the order you pick them; a mention moves someone up.",
    uyeSecin: "Choose at least one member.",
    siraEtiketi: (n: number) => `turn ${n}`,
    ekipBos: "There's nobody on the team yet.",
    kur: "Create channel",
    kuruldu: (kanal: string) => `#${kanal} is ready.`,
    kaydedildi: (kanal: string) => `#${kanal} was updated.`,
    kurulamadi: "Couldn't create the channel",
    kaydedilemedi: "Couldn't save the channel",
  },
};
