// Kod ekranı ve VS Code tezgâhı (İngilizce)
import type { kod as tr } from "../tr/kod";

export const kod: typeof tr = {
  baslik: "Code",
  yukleniyor: "Loading the code editor",
  yukleniyorMetni: "Loading the code editor…",
  acilamadi: "Couldn't open the code editor",
  ekranAcilamadi: "Couldn't open the Code screen.",
  dilNotu: "The editor switches language after a reload",
  dilNotuAyrinti: "VS Code can't change its language while running; it opens in the new language once the page reloads.",
  yenidenYukle: "Reload",
  genisEkranIster: "The code editor needs a wider screen",
  genisEkranAyrinti: "The VS Code editor opens at 760 pixels or wider. You can browse the workspace files below.",
  calismaAlani: "Workspace",
  dosyalarYukleniyor: "Loading files",
  anaRepo: (dal: string) => `${dal} · main repo`,
  ajanAlani: (ad: string, dal: string) => `${ad} · ${dal}`,
  ajan: "Agent",

  urunAdi: "ArnOrg Code",
  temaAdi: "FY Ink",
  dilAdi: "English",
  cekirdegeUlasilamadi: "Couldn't reach the core.",
  beklenmeyenYanit: (durum: number) => `Unexpected response (${durum}).`,
  bulunamadi: (yol: string) => `Not found: ${yol}`,
  gecersizAdres: (adres: string) => `Invalid ArnOrg address: ${adres}`,
  alanlarArasiTasima: "Files can't be moved between workspaces; copy and paste the file instead.",
  terminalAcilamadi: (hata: string) => `Couldn't open the terminal: ${hata}`,

  eklenti: {
    aciklama: "Work alongside ArnOrg agents: theme, search, agent badges and source control",
    rozetRengi: "Explorer badge color for files changed by an agent",
    komut: {
      duraklatVeDuzenle: "Pause and Edit",
      disaridaAc: "Open in External Editor",
      yenile: "Refresh",
      commit: "Commit",
      hazirla: "Stage Changes",
      hazirlaHepsi: "Stage All Changes",
      geriAl: "Unstage Changes",
      geriAlHepsi: "Unstage All Changes",
      at: "Discard Changes",
      dosyayiAc: "Open File",
      farkAc: "Open Changes",
    },
    degisiklik: {
      M: "Modified",
      A: "Added",
      D: "Deleted",
      R: "Renamed",
      C: "Copied",
      U: "Conflict",
      "?": "Untracked",
    },
    duzenliyor: (ad: string) => `${ad} is editing`,
    alanDegisikligi: (ad: string, tur: string) => `${ad} · ${tur.toLowerCase()}`,
    degistirdi: (ad: string) => `Changed by ${ad}`,
    durumOgesiAdi: "ArnOrg: agent editing this file",
    durumIpucu: (ad: string) => `${ad} is editing this file, so it's read-only for you. Click to pause ${ad} and take over editing.`,
    duzenleyenYok: "No agent is editing this file right now.",
    duraklatildi: (ad: string) =>
      `You paused ${ad}; editing is yours. When you save, the file is locked to agents for 30 seconds and the agent gets a "re-read" note.`,
    duraklatilamadi: (hata: string) => `Couldn't pause the agent: ${hata}`,
    disaridaAcilamadi: (hata: string) => `Couldn't open the external editor: ${hata}`,
    commitIpucu: "Commit message (Ctrl+Enter to commit)",
    grupCakisan: "Merge Changes",
    grupHazirlanan: "Staged Changes",
    grupDegisen: "Changes",
    grupTemel: "Changes against the base branch",
    grupTemelDal: (dal: string) => `Changes against ${dal}`,
    dalIpucu: (dal: string) => `${dal} branch · refresh`,
    islemBasarisiz: (islem: string, hata: string) => `${islem} failed: ${hata}`,
    islem: { hazirla: "Staging", geriAl: "Unstaging", at: "Discarding changes" },
    atilsinMi: (dosya: string) => `Discard the changes in ${dosya}? This can't be undone; an untracked file is deleted.`,
    atilsinMiCok: (n: number) => `Discard the changes in ${n} ${n === 1 ? "file" : "files"}? This can't be undone; untracked files are deleted.`,
    commitMesajiYazin: "Write a commit message.",
    commitYok: "There are no changes to commit.",
    hepsiCommitlensinMi: "There are no staged changes. Stage all changes and commit them?",
    hepsiniCommitEt: "Yes, commit all",
    commitAtildi: (sha: string) => `Committed: ${sha}`,
    commitBasarisiz: (hata: string) => `Commit failed: ${hata}`,
    farkTemel: (dosya: string, temel: string, ajan: string) => `${dosya} (${temel} ↔ ${ajan})`,
    farkHazirlanan: (dosya: string) => `${dosya} (HEAD ↔ Index)`,
    farkCalisma: (dosya: string) => `${dosya} (Index ↔ Working Tree)`,
    ajan: "agent",
  },
};
