// Kod zekâsı (İngilizce)
import { sayi } from "../../yardimcilar/bicim";
import type { kodZekasi as tr } from "../tr/kodZekasi";

const kac = (n: number, tekil: string, cogul: string) => `${sayi(n)} ${n === 1 ? tekil : cogul}`;

export const kodZekasi: typeof tr = {
  baslik: "Code intel",
  aciklama: "Semantic code search, symbols, repo map and link graph (imports and meaning) · agents work from the same index",
  calismaAlani: "Workspace",
  anaRepo: "Main repo",
  yenidenDizinle: "Re-index",
  yenidenDizinleIpucu: "Re-reads the files that changed",
  bolumEtiketi: "Code intel section",
  sekmeler: { arama: "Search", semboller: "Symbols", harita: "Map", grafik: "Graph" },
  sembolTuru: {
    fonksiyon: "function",
    metod: "method",
    sinif: "class",
    arayuz: "interface",
    tur: "type",
    enum: "enum",
    sabit: "constant",
    degisken: "variable",
    yapi: "struct",
    modul: "module",
    baslik: "heading",
    secici: "selector",
    tablo: "table",
  },
  eslesme: {
    anlamsal: "semantic",
    sozcuk: "keyword",
    sembol: "symbol name",
    karma: "several methods",
  },
  ornekSorgular: ["how errors are caught and logged", "authentication and sessions", "where the database connection is set up"],
  modelKapali: "Off",

  sure: (sn: number) => {
    if (sn < 90) return "under a minute";
    if (sn < 3600) return `~${Math.round(sn / 60)} min`;
    return `~${Math.floor(sn / 3600)} h ${Math.round((sn % 3600) / 60)} min`;
  },
  taraniyor: (taranan: number, toplam: number) => `Scanning files${toplam ? ` · ${sayi(taranan)}/${sayi(toplam)}` : ""}`,
  modelIndiriliyor: (yuzde: string) => `Downloading the semantic search model · ${yuzde} (first time only)`,
  kalan: (sure: string) => ` · ${sure} left`,
  hizliOneri: " · Settings → Code intel → Fast makes it several times quicker",
  gomuluyor: (gomulen: number, toplam: number, sure: string, oneri: string) =>
    `Building the semantic index · ${sayi(gomulen)}/${sayi(toplam)} chunks${sure}; keyword search already works${oneri}`,
  ozetEtiketi: "Index summary",
  dosya: "Files",
  sembol: "Symbols",
  parca: "Chunks",
  anlamsal: "Semantic",
  anlamsalIpucu: "Chunks with computed vectors",
  model: "Model",
  guncellendi: (ne: string) => `updated ${ne}`,
  henuzDizinlenmedi: "not indexed yet",
  dizinHatasi: "Index error",
  sozcukAramasiSurer: "Keyword search keeps working.",
  sifirdanDizinle: "Re-index from scratch",

  aramaEtiketi: "Code search",
  koddaAra: "Search the code",
  aramaIpucu: "What are you looking for? Ask in English or Turkish: “where does the order status change”",
  yolSuzgeci: "Path filter",
  yolIpucu: "Path or glob: src/server, **/*.tsx",
  benzeyenYerler: "places most similar to this code",
  aramayaDon: "Back to search",
  aranamadi: "Search failed",
  araniyor: "Searching…",
  sonucSayisi: (n: number, ms: number) => `${kac(n, "result", "results")} · ${sayi(ms)} ms`,
  sonucYok: "No results",
  dizinHazirDegil: "The semantic index isn't ready yet; found by keyword.",
  anlamsalKapali: "Semantic search is off (Settings → Code intel); found by keyword.",
  eslesenYok: "No matching code",
  eslesenYokAyrinti: "Try other words, clear the path filter or search by name on the Symbols tab.",
  aramaAciklama: "Ask in plain language: semantic search, keywords and symbol names are combined. Click a result to open the file at that line on the Code screen.",
  koddaAc: "Open on the Code screen",
  yontem: "The method that found this result",
  puan: (p: string) => `Score ${p}`,
  benzerleriBul: "Find places similar to this code",
  benzerleri: "Similar",
  satirdaAc: (yol: string, satir: number) => `Open ${yol} at line ${satir}`,

  sembollerEtiketi: "Symbols",
  sembolAra: "Search symbols",
  sembolIpucu: "Name or prefix: order, Store, useAuth",
  sembolTuruEtiketi: "Symbol type",
  tumTurler: "All types",
  sembolSayisi: (n: number, fazla: boolean) => (fazla ? "200+ symbols" : kac(n, "symbol", "symbols")),
  oneCikanlar: " · highlights",
  sembollerYukleniyor: "Loading symbols",
  disaAcik: "exported",
  sembolYok: "No symbols found",
  sembolYokAyrinti: "Try part of the name, or ask in plain language on the Search tab.",

  haritaYukleniyor: "Loading the map",
  dizinBos: "The index is empty",
  dizinBosAyrinti: "Files show up here once indexing finishes.",
  dosyaSatir: (dosya: number, satir: number) => `${kac(dosya, "file", "files")} · ${kac(satir, "line", "lines")}`,
  iceAktaranSayisi: "Number of files that import this file",
  klasorAgaci: "Folder tree",
  tumunuKapat: "Collapse all",
  dosyaAyrintisi: "File details",
  dosyaSecin: "Pick a file to see its symbols, what it imports and what uses it.",
  dilSatir: (dil: string, satir: number) => `${dil} · ${kac(satir, "line", "lines")}`,
  koddaAcKisa: "Open in Code",
  oneCikanSemboller: "Key symbols",
  turSatir: (tur: string, satir: number) => `${tur} · line ${satir}`,
  satir: (n: number) => `line ${n}`,
  bagimliliklarYukleniyor: "Dependencies…",
  iceAktardiklari: (n: number) => `Imports · ${n}`,
  bulunamadi: "not found",
  disPaket: "external package",
  iceAktarmaYok: "No imports.",
  onuKullananlar: (n: number) => `Used by · ${n}`,
  iceAktaranYok: "Nothing imports this file.",

  kok: "root",
  grafikEtiketi: "Code link graph",
  grafikDuzeyi: "Graph level",
  klasorler: "Folders",
  dosyalar: "Files",
  sigdir: "Fit",
  grafikBilgi: (dugum: number, baglanti: number, kirpilan: number) =>
    `${kac(dugum, "node", "nodes")} · ${kac(baglanti, "link", "links")}${kirpilan ? ` · ${kac(kirpilan, "node", "nodes")} didn't fit` : ""} · drag, scroll to zoom`,
  grafikHazirlaniyor: "Preparing the graph",
  bagimlilikYok: "No links",
  bagimlilikYokAyrinti: "No resolvable imports were found, and there are no meaning links yet or they are still being prepared.",
  grafikResmi: (n: number) => `Link graph with ${kac(n, "node", "nodes")}`,
  dugumBilgi: (id: string, dosya: number, satir: number) => `${id} · ${kac(dosya, "file", "files")} · ${kac(satir, "line", "lines")}`,
  dugumAyrintisi: "Node details",
  dugumSecin:
    "Click a node to see its import links and the files closest in meaning. Node size shows line count; a solid line is an import (thickness shows how many), a dashed coral line is a meaning link.",
  kokKlasor: "Root folder",
  karisik: "mixed",
  dugumOzeti: (dil: string, dosya: number, satir: number) => `${dil} · ${kac(dosya, "file", "files")} · ${kac(satir, "line", "lines")}`,
  kullandiklari: (n: number) => `Uses · ${n}`,
  yok: "None.",

  bagTurleri: "Link types",
  iceAktarma: "Imports",
  anlam: "Meaning",
  iceAktarmaIpucu: "Solid line: one file imports or references the other (in the arrow's direction)",
  anlamIpucu: "Dashed coral line: their code is close in meaning (from the search index embeddings)",
  anlamHazirlaniyor: (gomulen: number, toplam: number) => `Preparing meaning links · ${sayi(gomulen)}/${sayi(toplam)} chunks embedded; import links already show.`,
  anlamGuncelleniyor: (gomulen: number, toplam: number) => `Updating meaning links · ${sayi(gomulen)}/${sayi(toplam)} chunks embedded; showing the last computed ones.`,
  anlamKapali: "Meaning links are off: pick an embedding model in Settings → Code intel. Import links show.",
  anlamKirpildi: (n: number) => `Large repository: meaning links weren't searched in ${kac(n, "file", "files")} (largest files first).`,
  bagGizli: "Link types hidden",
  bagGizliAyrinti: "Turn on a link type with the Imports or Meaning button above.",
  anlamcaYakin: (n: number) => `Close in meaning · ${n}`,
  benzerlik: "How similar their code is",
  ithalIle: "also linked by an import",
  enYakinKod: "Closest code",
  parcaAdi: (sembol: string | null, bas: number) => sembol ?? `line ${bas}`,
};
