// İlk kurulum sihirbazı, Claude Code ve GitHub kurulumu, klasör seçici, proje açma (İngilizce)
import type { kurulum as tr } from "../tr/kurulum";

export const kurulum: typeof tr = {
  sihirbaz: {
    baslik: "First-run setup",
    adimlarEtiket: "Setup steps",
    adimlar: { dil: "Language", claude: "Claude Code", github: "GitHub", proje: "First project", hazirlik: "Kickoff" },
    hazir: "ready",
    hazirligiAtla: "Skip setup",
    atlandi: "Setup skipped. You can reopen it from Settings at any time.",
    bitti: "Setup complete. You can reopen it from Settings at any time.",
    geri: "Back",
    sonra: "Later",
    devam: "Continue",
  },
  dil: {
    baslik: "Hello. Let's pick a language first.",
    aciklama:
      "I'm ArnOrg. In a few steps we'll get your company of Claude Code agents ready together: Claude sign-in, GitHub, your first project and a first meeting with your CEO. Skip any step you like and come back to it from Settings.",
    secimEtiket: "Interface language",
    selam: "Let's set up in English.",
    ipucu: "Your agents will speak it too; you can change it in Settings.",
  },
  liste: { tamam: "ready", eksik: "missing", hata: "needs attention", bilgi: "optional" },
  claude: {
    baslik: "Let's connect your Claude account.",
    baslikHazir: "Claude Code is ready.",
    aciklama:
      "Your agents run on this computer's Claude Code sign-in. ArnOrg works only with a Claude subscription (Pro, Max or Team); API keys aren't used.",
    aciklamaHazir: (eposta: string | null) => `You're signed in${eposta ? ` as ${eposta}` : ""} with a Claude subscription. We can move on.`,
    yukleniyor: "Checking Claude Code…",
    alinamadi: "Couldn't read the setup status",
    kopya: "Claude Code",
    kaynak: { paket: "Bundled with ArnOrg", sistem: "System claude command", ayar: "Path from Settings" },
    kopyaYok: "Not found",
    surum: (s: string) => `version ${s}`,
    kopyaYokUyari: "Claude Code wasn't found. Install it for the terminal or set its path in Settings.",
    giris: "Sign-in",
    girisYapildi: "Signed in",
    girisYok: "Not signed in",
    girisYap: "Sign in with your Claude account",
    girisIpucu: "Claude's sign-in page opens in your browser. If the page shows a code after you sign in, paste it here.",
    abonelik: "Subscription",
    abonelikVar: "Claude subscription",
    abonelikYok: "API key or Console sign-in",
    abonelikBekliyor: "Checked after sign-in",
    apiUyari:
      "This sign-in uses an API key or a Console account. ArnOrg works only with a Claude subscription; sign in again with your Pro, Max or Team account.",
    yenidenGiris: "Sign in again with a subscription",
    terminal: "Terminal command",
    terminalVar: "claude command installed",
    terminalYok: "Not installed · optional",
    terminalAciklama:
      "Agents use ArnOrg's own copy. You only need this if you also want to run claude in your terminal.",
    terminalKur: "Also install for the terminal",
    girisTamam: "Signed in to Claude.",
    kurulumTamam: "The claude command is installed.",
    tazele: "Refresh status",
  },
  github: {
    baslik: "Shall we connect GitHub?",
    baslikHazir: "GitHub is connected.",
    aciklama:
      "Optional. Once connected, you can pick a repository and clone it, create new projects on GitHub too, and push approved work to the remote. ArnOrg sets up gh and git for you.",
    aciklamaHazir: (kullanici: string) => `You're connected as ${kullanici} and your git identity is set. We can move on.`,
    yukleniyor: "Checking GitHub and git…",
    git: "git",
    gitVar: (surum: string | null) => (surum ? `git ${surum}` : "Installed"),
    gitYok: "Not found",
    gitLinux: "Install git with your package manager, then refresh the status:",
    gitKur: "Install git",
    gitKurWindows: "Installs Git for Windows with winget.",
    gitKurMac: "macOS opens its developer tools installer; refresh the status when it's done.",
    gitOnce: "Install git first.",
    gh: "GitHub CLI",
    ghVar: (surum: string | null, kaynak: string) => `${surum ? `gh ${surum}` : "gh"} · ${kaynak}`,
    ghKaynak: { sistem: "system", arnorg: "ArnOrg's copy", ayar: "path from Settings" },
    ghYok: "Not installed",
    ghKur: "Install GitHub CLI",
    ghKurIpucu: "ArnOrg downloads gh from GitHub into its own folder; no admin rights needed.",
    ghKuruldu: "GitHub CLI is installed.",
    giris: "GitHub sign-in",
    girisVar: (kullanici: string) => `Connected as ${kullanici}`,
    girisYok: "Not signed in",
    girisOnce: "Install GitHub CLI first.",
    girisYap: "Sign in to GitHub",
    girisIpucu: "GitHub opens in your browser; enter the one-time code and approve. git is also set up to use gh for GitHub credentials.",
    girisTamam: (kullanici: string | null) => (kullanici ? `Connected to GitHub as ${kullanici}.` : "Connected to GitHub."),
    yardimciYok: "git doesn't use gh for GitHub credentials yet.",
    yardimciAyarla: "Set up git with gh",
    yardimciTamam: "git now uses gh for GitHub credentials.",
    kimlik: "git identity",
    kimlikVar: (ad: string, eposta: string) => `${ad} · ${eposta}`,
    kimlikYok: "Name and email are empty",
    kimlikIpucu: "Your agents' commits use this name and email.",
    kimlikGithubdan: "Filled in from your GitHub account; change it if you like.",
    ad: "Name",
    adOrnek: "Ada Lovelace",
    eposta: "Email",
    epostaOrnek: "ada@example.com",
    adGerekli: "Name is required.",
    epostaGecersiz: "Enter a valid email address.",
    kimlikKaydet: "Save identity",
    kimlikDegistir: "Change",
    kimlikKaydedildi: "git identity saved.",
    tazele: "Refresh status",
  },
  islem: {
    adlar: {
      claude_giris: "Claude sign-in",
      claude_kur: "Claude Code install",
      gh_kur: "GitHub CLI install",
      gh_giris: "GitHub sign-in",
      git_kur: "git install",
      klonla: "Clone",
      github_olustur: "GitHub repository",
    },
    durumlar: { calisiyor: "In progress", tamam: "Done", hata: "Failed", iptal: "Cancelled" },
    gecen: (sure: string) => `${sure} elapsed`,
    iptal: "Cancel",
    gizle: "Dismiss",
    yenidenDene: "Try again",
    cikti: "Full output",
    ciktiYok: "No output yet.",
    adresAcildi: "The sign-in page opened in your browser.",
    adresAc: "Didn't open? Open it here",
    kodYapistir: "Paste the code shown on the page",
    kodOrnek: "Paste the code here",
    kodGerekli: "Paste the code.",
    kodGonder: "Submit",
    kodDogrulaniyor: "Checking the code…",
    girisBekleniyor: "Waiting for you to finish signing in…",
    cihazKodu: "One-time code",
    cihazKoduIpucu: "Enter this code on the GitHub page.",
    cihazSayfasi: "Open github.com/login/device",
    onayBekleniyor: "Waiting for you to approve on GitHub…",
    ilerleme: "Progress",
    asamalar: { indirme: "Downloading", alma: "Receiving objects", cozme: "Resolving deltas" },
  },
  proje: {
    baslik: "Let's open your first project.",
    baslikHazir: (ad: string) => `${ad} is open.`,
    aciklama:
      "Start a new project, clone a repository from GitHub, or connect a folder on your computer. ArnOrg suggests the location; there's no path to type.",
    varOlan: (n: number) =>
      n === 1 ? "You already have a project. Open another one or skip this step." : `You already have ${n} projects. Open another one or skip this step.`,
    kok: (yol: string) => `New projects open under ${yol}.`,
  },
  hazirlik: {
    baslik: "Your CEO is ready for you.",
    aciklama:
      "In #ceo, your CEO talks the project through with you, one topic at a time. What you say is saved to memory as board decisions; the constitution and new hires come to you for approval.",
    konularBaslik: "On the agenda",
    konular: ["The goal and what the first release must have", "Your technology and quality preferences", "The constitution: rules the team follows", "First hires"],
    proje: "Project",
    dal: "Working branch",
    uzak: "Remote",
    uzakYok: "None",
    baslat: "Start the kickoff",
    sonra: "Not now",
    sonraIpucu: "You can start the conversation later from Headquarters.",
    basladi: "Kickoff started. Your CEO is asking the first question in #ceo.",
    suruyor: (ad: string) => `The kickoff for ${ad} is in progress.`,
    tamam: (ad: string) => `The kickoff for ${ad} is done.`,
    karargah: "Go to Headquarters",
    projeYok: "Open a project first to start the kickoff.",
    projeyeDon: "Back to the project step",
    bitir: "Finish setup",
  },
  ac: {
    sekmeEtiket: "Where should the project come from?",
    sekmeler: { yeni: "New project", github: "From GitHub", klasor: "Folder on this computer" },
    ad: "Project name",
    adOrnek: "Order Panel",
    adGerekli: "Project name is required.",
    aciklama: "Description (optional)",
    aciklamaOrnek: "Order and shipping tracking for small businesses",
    dal: "Working branch",
    dalIpucu: "Agents branch off it; approved merges go into it.",
    dalGecersiz: "Enter a valid branch name (no spaces, .. or ~^:?*[).",
    github: "Also create a GitHub repository",
    githubIpucu: "The repository is created and the project scaffold is pushed as the first commit.",
    githubYok: "GitHub isn't connected.",
    githubBagla: "Connect GitHub",
    gorunurluk: "Visibility",
    ozel: "Private",
    acik: "Public",
    sahip: "Owner",
    sahipSiz: (kullanici: string) => `${kullanici} (you)`,
    olustur: "Create project",
    acilamadi: "Couldn't open the project",
    acildi: (ad: string) => `${ad} is open. A CEO has been hired.`,
  },
  konum: {
    etiket: "Location",
    ipucu: "The project folder is created here.",
    degistir: "Change",
    varsayilan: "Use default",
    elle: "Type a path",
    elleKapat: "Back to automatic location",
    elleEtiket: "Full folder path",
    elleOrnek: "/home/you/projects/order-panel",
    mutlak: "Enter an absolute path (e.g. /home/you/projects/order-panel).",
    secBaslik: "Choose where to create the project",
    adYeri: "project-name",
  },
  depo: {
    ara: "Search repositories",
    araOrnek: "Repository name or description",
    liste: "Your repositories",
    yukleniyor: "Loading repositories…",
    alinamadi: "Couldn't load repositories",
    bos: "Your account has no repositories yet.",
    eslesmeYok: (q: string) => `No repositories match “${q}”.`,
    ozel: "Private",
    acik: "Public",
    bosDepo: "empty",
    guncellendi: (zaman: string) => `updated ${zaman}`,
    secin: "Pick a repository from the list.",
    dallarAlinamadi: "Couldn't load branches",
    projeAdi: "Project name",
    klonla: "Clone and open",
    girisGerekli: "Let's connect GitHub first so we can list your repositories.",
    acildi: (ad: string) => `${ad} is cloned and open.`,
  },
  dal: {
    varsayilan: "default",
    korumali: "protected",
    yeni: "New branch…",
    yeniAd: "New branch name",
    yeniOrnek: "develop",
    listeyeDon: "Pick from list",
    bosDepo: "The repository is empty; the working branch will be created with this name.",
    yukleniyor: "Loading branches…",
    yerel: "On this computer",
    uzak: "On the remote",
  },
  klasor: {
    aciklama: "Connect a git repository on your computer. Your files stay untouched; only an .arnorg/ folder is added.",
    sec: "Choose folder",
    baska: "Choose another",
    secBaslik: "Choose the folder to connect",
    secilen: "Selected folder",
    denetleniyor: "Checking the folder…",
    denetlenemedi: "Couldn't check the folder",
    repo: "git repository",
    repoDegil: "not a git repository",
    repoDegilAciklama:
      "This folder isn't a git repository yet. ArnOrg can start one here: it runs git init and commits the folder's current files.",
    dalNotu: "The working branch will be the repository's current branch; you can change it in Project settings.",
    bagla: "Connect repository",
    baslat: "Start a repository here",
  },
  gezgin: {
    baslik: "Choose a folder",
    kisayollar: "Shortcuts",
    konum: "Location",
    ust: "Parent folder",
    yukleniyor: "Loading folders…",
    alinamadi: "Couldn't read the folder",
    evDon: "Go to home folder",
    bos: "No subfolders here.",
    repo: "git",
    repoBaslik: "This folder is a git repository",
    klasorler: "Subfolders",
    yeniKlasor: "New folder",
    yeniKlasorAd: "New folder name",
    olustur: "Create",
    yolYaz: "Type path",
    yolEtiket: "Folder path",
    yolGit: "Go",
    secilecek: "Selected",
    sec: "Choose this folder",
    klavye: "Use the arrow keys to move, Enter to open, Backspace to go up.",
  },
};
