// Ofis (İngilizce)
import type { ofis as tr } from "../tr/ofis";

const kisi = (n: number, tekil: string, cogul: string) => `${n} ${n === 1 ? tekil : cogul}`;

export const ofis: typeof tr = {
  baslik: "Office",
  sahneEtiketi: "Office scene",
  haritaEtiketi: "Office map. Press + and - to zoom, 0 to fit, arrow keys to pan",
  sayacEtiketi: "Employees by status",
  akisBaslik: "In the office now",
  kameraEtiketi: "Camera",
  yayinKapali: "Reduced motion is on: the live view is unavailable",
  akisBos: "Quiet. When someone talks, hands in work or walks through the door, it shows up here.",
  yakinlastirmaEtiketi: "Zoom",
  yakinlastir: "Zoom in",
  yakinlastirIpucu: "Zoom in (+)",
  uzaklastir: "Zoom out",
  uzaklastirIpucu: "Zoom out (-)",
  sigdir: "Fit the office",
  sigdirIpucu: "Fit (0)",
  yayin: "Live view",
  yayinIpucu: "The camera wanders between people and events on its own. Dragging or zooming stops it.",
  yayinda: (ad: string) => `On air: ${ad}`,
  yayinAriyor: "Looking for a scene",
  takipEt: "Follow",
  takipEtIpucu: (ad: string) => `Keep the camera on ${ad}`,
  takipte: (ad: string) => `Following: ${ad}`,
  takipBirak: "Stop following",
  seritEtiketi: "Latest events. Press one to move the camera there",
  olayaGit: (metin: string) => `Move the camera: ${metin}`,
  cizilemedi: "Couldn't draw the office",
  projeVerisiAlinamadi: "Couldn't load the project data.",
  hazirlaniyor: "Setting up the office",
  varliklarAlinamadi: (durum: number) => `Couldn't load the office assets (${durum}).`,

  odalar: {
    ceo: { ad: "CEO", alt: "management" },
    cto: { ad: "CTO", alt: "tech lead" },
    toplanti: { ad: "Meetings", alt: "#meetings" },
    arsiv: { ad: "Archive", alt: "memory · notes" },
    sunucu: { ad: "Servers", alt: "main branch" },
    muhendislik: { ad: "Engineering", alt: "open office" },
    dinlenme: { ad: "Lounge", alt: "coffee · water · chat" },
    kurul: { ad: "Board", alt: "approval table · entrance" },
    arastirma: { ad: "Library", alt: "research · web sources" },
    laboratuvar: { ad: "Test Lab", alt: "tests · builds" },
    studyo: { ad: "Studio", alt: "delivery · design" },
  },
  giris: "ENTRANCE",
  yerel: "en-US",

  sicak: {
    kurul: "Board table: open Approvals",
    pano: "Task board: open Board",
    sunucu: "Server room: open Code",
    arsiv: "Archive: open Notes",
    toplanti: "Meeting room: open #meetings",
    arastirma: "Library screen: open Notes",
    laboratuvar: "Test board: open Approvals (quality gate)",
    studyo: "Presentation screen: open Approvals (deliveries)",
  },
  ekran: {
    arastirma: "RESEARCH",
    arastirmaBos: "Waiting for a source",
    test: "TESTS",
    testDurum: { bos: "Idle", hazirlik: "Preparing", kosuyor: "Running", gecti: "Passed", kaldi: "Failed" },
    testBos: "No recent run",
    sunum: "DEMO",
    sunumBos: "Empty stage",
    sunumDurum: { bekliyor: "Waiting for the board", onaylandi: "Accepted", reddedildi: "Feedback", zaman_asimi: "Expired" },
  },
  pano: {
    ad: "TASKS",
    sutunlar: { bekleyen: "Backlog", suruyor: "In progress", inceleme: "Review", tamam: "Done" },
    etiket: (bekleyen: number, suren: number, incelemede: number, tamam: number) =>
      `Task board: ${bekleyen} waiting, ${suren} in progress, ${incelemede} in review, ${tamam} done. Open Board`,
  },
  kurulAd: "Board",
  kurulMasasi: (n: number) =>
    n ? `Board table: ${kisi(n, "approval", "approvals")} pending. Open Approvals` : "Board table: no pending approvals. Open Approvals",
  aday: "Candidate",
  adayEtiketi: (ad: string) => `Candidate: ${ad}. Open the hiring proposal`,
  kararIsareti: (ad: string) => `${ad} is waiting for your decision: open the approval`,
  kararIsaretiIpucu: "Waiting for your decision: open the approval",
  gozetmenHatirlatti: "Reminded by the supervisor",

  kisiEtiketi: (ad: string, rol: string, durum: string, etkinlik: string) => `${ad}, ${rol}, ${durum}: ${etkinlik}`,

  etkinlik: {
    yeniGeldi: "Just arrived",
    yerlesiyor: "Settling in at the desk",
    ayriliyor: "Leaving the office",
    tanisiyor: (ad: string) => `Meeting ${ad}`,
    konusuyor: (ad: string) => `Talking with ${ad}`,
    kanalaYaziyor: (kanal: string) => `Writing in #${kanal}`,
    incelemeyeGoturuyor: (kod: string) => `Taking ${kod} to review`,
    arsiveNot: "Leaving a note in the archive",
    soruSoruyor: (ad: string) => `Asking ${ad} a question`,
    toplantiyaGidiyor: "Heading to a meeting",
    toplantida: "In a meeting",
    masasindaCalisiyor: (is: string) => `Working at the desk${is ? ` · ${is}` : ""}`,
    masasinaGidiyor: "Heading to the desk",
    kurulBekliyor: "Waiting for your decision at the board table",
    kahveIciyor: "Having coffee in the lounge",
    suIciyor: "Getting some water",
    isBekliyor: "In the lounge, waiting for work",
    kapali: "Session closed · at the desk",
    duraklatildi: "Paused by the board",
    hata: "Session error",
    panoda: "At the task board",
    kisiyle: (ad: string) => `With ${ad}`,
    arsivde: "Going through notes in the archive",
    kurulda: "At the board table",
    tahtada: "Preparing a report at the whiteboard",
    sunucuda: "In the server room",
    arastirmada: "Researching the web in the library",
    laboratuvarda: "Running tests in the test lab",
    sunumda: "Presenting a delivery to the board in the studio",
    tasarimda: "Working on design in the studio",
    tanitimda: "Writing the showcase page in the studio",
    uyukluyor: "Dozing off in the lounge",
    dusunuyor: (etkinlik: string) => `${etkinlik} · thinking`,
  },

  balon: {
    hosGeldin: (ad: string) => `Welcome, ${ad}! Your desk is ready.`,
    tesekkurler: "Thanks, getting started.",
    incelemeyeHazir: (kod: string) => `${kod} is ready for review`,
    bakiyorum: "On it.",
    notAldi: (baslik: string) => `noted: ${baslik}`,
    yanitladim: "Answered.",
    yanitGelmedi: "No answer.",
    tamam: (kod: string) => `${kod} done`,
    toplanti: (gundem: string) => `Meeting: ${gundem}`,
    testGecti: (komut: string) => `${komut} · passed`,
    testKaldi: (komut: string) => `${komut} · failed`,
    teslim: (baslik: string) => `Delivery: ${baslik}`,
    kurul: "Board",
    kod: "[code]",
  },

  akis: {
    yeniGorev: (kod: string, baslik: string) => `New task ${kod}: ${baslik}`,
    geldi: (ad: string, rol: string) => `${ad} joined the office · ${rol}`,
    kurulMasasinda: (ad: string) => `${ad} is waiting for your decision at the board table`,
    masasinaDondu: (ad: string) => `${ad} is back at the desk`,
    oturumHatasi: (ad: string) => `${ad}: session error`,
    ayrildi: (ad: string) => `${ad} left the office`,
    kurulKanala: (kanal: string, metin: string) => `Board #${kanal}: ${metin}`,
    kuruldan: (adlar: string, metin: string) => `Board → ${adlar}: ${metin}`,
    toplanti: (ad: string, gundem: string, katilimcilar: string) => `Meeting · ${ad}: ${gundem} · ${katilimcilar}`,
    toplantiMesaji: (ad: string, metin: string) => `Meeting · ${ad}: ${metin}`,
    toplantiGorusYok: (ad: string) => `Meeting · ${ad} gave no input`,
    mesaj: (ad: string, alicilar: string, metin: string) => `${ad} → ${alicilar}: ${metin}`,
    kanalMesaji: (ad: string, kanal: string, metin: string) => `${ad} #${kanal}: ${metin}`,
    notAldi: (ad: string, baslik: string) => `${ad} noted: ${baslik}`,
    soru: (soran: string, sorulu: string, soru: string) => `${soran} → ${sorulu}: ${soru}`,
    yanitladi: (ad: string, yanit: string) => `${ad} answered: ${yanit}`,
    yanitVermedi: (soran: string, sorulu: string) => `${soran}: ${sorulu} didn't answer`,
    gozetmen: (metin: string) => `Supervisor: ${metin}`,
    incelemeyeHazir: (sahip: string, inceleyen: string, kod: string) => `${sahip} → ${inceleyen}: ${kod} is ready for review`,
    incelemede: (kod: string) => `${kod} is in review`,
    tamamlandi: (kod: string, ad: string | null) => `${kod} done${ad ? ` · ${ad}` : ""}`,
    gorevDurumu: (kod: string, durum: string) => `${kod} → ${durum}`,
    adayKapida: (ad: string) => `Candidate at the door: ${ad}`,
    onay: (ad: string, baslik: string) => `${ad}: ${baslik}`,
    adayKabulEdilmedi: (ad: string) => (ad ? `Candidate ${ad} was not accepted` : "The candidate was not accepted"),
    onaylandi: (baslik: string) => `${baslik}: approved`,
    reddedildi: (baslik: string) => `${baslik}: rejected`,
    suresiDoldu: (baslik: string) => `${baslik}: expired`,
    arastirma: (ad: string, konu: string) => (konu ? `${ad} in the library: ${konu}` : `${ad} is researching in the library`),
    laboratuvar: (ad: string, komut: string) => `${ad} in the lab: ${komut}`,
    testGecti: (ad: string, komut: string) => `${ad}: ${komut} passed`,
    testKaldi: (ad: string, komut: string) => `${ad}: ${komut} failed`,
    teslim: (ad: string, baslik: string) => `${ad} is presenting a delivery in the studio: ${baslik}`,
    teslimKabul: (baslik: string) => `Delivery accepted: ${baslik}`,
    teslimGeri: (baslik: string) => `Feedback on the delivery: ${baslik}`,
    tasarim: (ad: string) => `${ad} is working on design in the studio`,
    tanitim: (ad: string) => `${ad} is writing the showcase page in the studio`,
  },
  ekip: "Team",

  ozet: (calisan: number, parcalar: string[], bekleyen: number) =>
    `${kisi(calisan, "employee", "employees")} in the office${parcalar.length ? `: ${parcalar.join(", ")}` : ""}. ${
      bekleyen ? `${kisi(bekleyen, "approval", "approvals")} pending at the board table` : "No pending approvals at the board table"
    }.`,
};
