// Ofis (İngilizce)
import type { ofis as tr } from "../tr/ofis";

const kisi = (n: number, tekil: string, cogul: string) => `${n} ${n === 1 ? tekil : cogul}`;

export const ofis: typeof tr = {
  baslik: "Office",
  sahneEtiketi: "Office scene",
  haritaEtiketi: "Office map. Press + and - to zoom, 0 to fit, arrow keys to pan",
  sayacEtiketi: "Employees by status",
  akisBaslik: "In the office now",
  akisEtiketi: "Latest scenes",
  akisBos: "Quiet. When someone talks, hands in work or walks through the door, it shows up here.",
  yakinlastirmaEtiketi: "Zoom",
  yakinlastir: "Zoom in",
  yakinlastirIpucu: "Zoom in (+)",
  uzaklastir: "Zoom out",
  uzaklastirIpucu: "Zoom out (-)",
  sigdir: "Fit the office",
  sigdirIpucu: "Fit (0)",
  cizilemedi: "Couldn't draw the office",
  projeVerisiAlinamadi: "Couldn't load the project data.",
  hazirlaniyor: "Setting up the office",
  varliklarAlinamadi: (durum: number) => `Couldn't load the office assets (${durum}).`,

  odalar: {
    ceo: { ad: "CEO", alt: "management" },
    cto: { ad: "CTO", alt: "tech lead" },
    toplanti: { ad: "Meetings", alt: "#meetings" },
    arsiv: { ad: "Archive", alt: "memory · notes" },
    sunucu: { ad: "Servers", alt: "main branch" },
    muhendislik: { ad: "Engineering", alt: "open office" },
    dinlenme: { ad: "Lounge", alt: "coffee · water · chat" },
    kurul: { ad: "Board", alt: "approval table · entrance" },
  },
  giris: "ENTRANCE",
  yerel: "en-US",

  sicak: {
    kurul: "Board table: open Approvals",
    pano: "Task board: open Board",
    sunucu: "Server room: open Code",
    arsiv: "Archive: open Notes",
    toplanti: "Meeting room: open #meetings",
  },
  pano: {
    ad: "TASKS",
    sutunlar: { bekleyen: "Backlog", suruyor: "In progress", inceleme: "Review", tamam: "Done" },
    etiket: (bekleyen: number, suren: number, incelemede: number, tamam: number) =>
      `Task board: ${bekleyen} waiting, ${suren} in progress, ${incelemede} in review, ${tamam} done. Open Board`,
  },
  kurulAd: "Board",
  kurulMasasi: (n: number) =>
    n ? `Board table: ${kisi(n, "approval", "approvals")} pending. Open Approvals` : "Board table: no pending approvals. Open Approvals",
  aday: "Candidate",
  adayEtiketi: (ad: string) => `Candidate: ${ad}. Open the hiring proposal`,
  kararIsareti: (ad: string) => `${ad} is waiting for your decision: open the approval`,
  kararIsaretiIpucu: "Waiting for your decision: open the approval",
  gozetmenHatirlatti: "Reminded by the supervisor",

  kisiEtiketi: (ad: string, rol: string, durum: string, etkinlik: string) => `${ad}, ${rol}, ${durum}: ${etkinlik}`,

  etkinlik: {
    yeniGeldi: "Just arrived",
    yerlesiyor: "Settling in at the desk",
    ayriliyor: "Leaving the office",
    tanisiyor: (ad: string) => `Meeting ${ad}`,
    konusuyor: (ad: string) => `Talking with ${ad}`,
    kanalaYaziyor: (kanal: string) => `Writing in #${kanal}`,
    incelemeyeGoturuyor: (kod: string) => `Taking ${kod} to review`,
    birlesiyor: (kod: string) => `Merging ${kod} into main`,
    arsiveNot: "Leaving a note in the archive",
    soruSoruyor: (ad: string) => `Asking ${ad} a question`,
    toplantiyaGidiyor: "Heading to a meeting",
    toplantida: "In a meeting",
    masasindaCalisiyor: (is: string) => `Working at the desk${is ? ` · ${is}` : ""}`,
    masasinaGidiyor: "Heading to the desk",
    kurulBekliyor: "Waiting for your decision at the board table",
    kahveIciyor: "Having coffee in the lounge",
    suIciyor: "Getting some water",
    isBekliyor: "In the lounge, waiting for work",
    kapali: "Session closed · at the desk",
    duraklatildi: "Paused by the board",
    hata: "Session error",
    panoda: "At the task board",
    kisiyle: (ad: string) => `With ${ad}`,
    arsivde: "Going through notes in the archive",
    kurulda: "At the board table",
    tahtada: "Preparing a report at the whiteboard",
    okumada: "Researching in the reading corner",
    sunucuda: "In the server room",
  },

  balon: {
    hosGeldin: (ad: string) => `Welcome, ${ad}! Your desk is ready.`,
    tesekkurler: "Thanks, getting started.",
    incelemeyeHazir: (kod: string) => `${kod} is ready for review`,
    bakiyorum: "On it.",
    birlesti: (kod: string) => `${kod} merged into main`,
    notAldi: (baslik: string) => `noted: ${baslik}`,
    yanitladim: "Answered.",
    yanitGelmedi: "No answer.",
    tamam: (kod: string) => `${kod} done`,
    toplanti: (gundem: string) => `Meeting: ${gundem}`,
    kurul: "Board",
    kod: "[code]",
  },

  akis: {
    yeniGorev: (kod: string, baslik: string) => `New task ${kod}: ${baslik}`,
    geldi: (ad: string, rol: string) => `${ad} joined the office · ${rol}`,
    kurulMasasinda: (ad: string) => `${ad} is waiting for your decision at the board table`,
    masasinaDondu: (ad: string) => `${ad} is back at the desk`,
    oturumHatasi: (ad: string) => `${ad}: session error`,
    ayrildi: (ad: string) => `${ad} left the office`,
    kurulKanala: (kanal: string, metin: string) => `Board #${kanal}: ${metin}`,
    kuruldan: (adlar: string, metin: string) => `Board → ${adlar}: ${metin}`,
    toplanti: (ad: string, gundem: string, katilimcilar: string) => `Meeting · ${ad}: ${gundem} · ${katilimcilar}`,
    toplantiMesaji: (ad: string, metin: string) => `Meeting · ${ad}: ${metin}`,
    toplantiGorusYok: (ad: string) => `Meeting · ${ad} gave no input`,
    mesaj: (ad: string, alicilar: string, metin: string) => `${ad} → ${alicilar}: ${metin}`,
    kanalMesaji: (ad: string, kanal: string, metin: string) => `${ad} #${kanal}: ${metin}`,
    notAldi: (ad: string, baslik: string) => `${ad} noted: ${baslik}`,
    soru: (soran: string, sorulu: string, soru: string) => `${soran} → ${sorulu}: ${soru}`,
    yanitladi: (ad: string, yanit: string) => `${ad} answered: ${yanit}`,
    yanitVermedi: (soran: string, sorulu: string) => `${soran}: ${sorulu} didn't answer`,
    gozetmen: (metin: string) => `Supervisor: ${metin}`,
    incelemeyeHazir: (sahip: string, inceleyen: string, kod: string) => `${sahip} → ${inceleyen}: ${kod} is ready for review`,
    incelemede: (kod: string) => `${kod} is in review`,
    tamamlandi: (kod: string, ad: string | null) => `${kod} done${ad ? ` · ${ad}` : ""}`,
    gorevDurumu: (kod: string, durum: string) => `${kod} → ${durum}`,
    adayKapida: (ad: string) => `Candidate at the door: ${ad}`,
    birlestirmeBekliyor: (baslik: string) => `${baslik}: waiting for board approval`,
    onay: (ad: string, baslik: string) => `${ad}: ${baslik}`,
    birlesti: (kod: string) => `${kod} merged into main`,
    adayKabulEdilmedi: (ad: string) => (ad ? `Candidate ${ad} was not accepted` : "The candidate was not accepted"),
    onaylandi: (baslik: string) => `${baslik}: approved`,
    reddedildi: (baslik: string) => `${baslik}: rejected`,
    suresiDoldu: (baslik: string) => `${baslik}: expired`,
  },
  ekip: "Team",
  dal: "Branch",

  ozet: (calisan: number, parcalar: string[], bekleyen: number) =>
    `${kisi(calisan, "employee", "employees")} in the office${parcalar.length ? `: ${parcalar.join(", ")}` : ""}. ${
      bekleyen ? `${kisi(bekleyen, "approval", "approvals")} pending at the board table` : "No pending approvals at the board table"
    }.`,
};
