// Onaylar (İngilizce)
import type { onaylar as tr } from "../tr/onaylar";

export const onaylar: typeof tr = {
  baslik: "Approvals",
  altBaslik: "Hiring, merges into main and irreversible decisions go through you",
  tureGore: "Filter by type",
  butunTurler: "All types",
  durum: {
    bekliyor: "Pending",
    onaylandi: "Approved",
    reddedildi: "Rejected",
    zaman_asimi: "Expired",
  },
  alinamadi: "Couldn't load approvals.",

  bekleyenler: "Pending decisions",
  bekleyenYok: "No pending decisions",
  bekleyenYokMetin: "When the CEO proposes a hire or a piece of work is ready to go into main, you decide here.",
  turdeBekleyenYok: "No pending decisions of this type",

  gecmis: "History",
  sonucaGore: "Filter by outcome",
  gecmisYok: "Nothing decided yet",
  gecmisYokMetin: "Your decisions collect here, along with your notes.",
  suzgecteYok: "Nothing matches this filter",
  suzgeciDegistirin: "Change the filter.",
  dahaGoster: (n: number) => `Show ${n} more`,

  kim: {
    ise_alim: "Proposed by",
    birlestirme: "Requested by",
    genel: "Asked by",
    arac: "Requested by",
    anayasa: "Proposed by",
    isten_cikarma: "Proposed by",
    teslim: "Delivered by",
  },
  bilinmeyenAjan: "Unknown agent",
  oturumunuAc: (ad: string) => `Open ${ad}'s session`,
  sureYok: "No deadline",
  kaldi: (sure: string) => `${sure} left`,
  sureDoldu: "Time's up · will be rejected",
  sureIpucu: "Rejected automatically when time runs out",

  sonra: {
    ise_alim: "If approved",
    birlestirme: "If approved",
    genel: "If approved",
    arac: "If allowed",
    anayasa: "If approved",
    isten_cikarma: "If approved",
    teslim: "If accepted",
  },
  etki: {
    iseAlim: (ad: string, rol: string, yonetici: string | null) =>
      `${ad} joins the team as ${rol} and reports to ${yonetici ?? "the board directly"}; a workspace is set up for them.`,
    birlestirme: (dal: string, hedef: string) => `${dal} is merged into ${hedef}; tasks in review move to Done.`,
    genel: (ajan: string) => `${ajan} gets your decision and goes ahead accordingly; your note is passed on as the answer.`,
    arac: (ajan: string, arac: string) => `${ajan} runs this ${arac} call.`,
    anayasa: (madde: number) => `The constitution takes effect with ${madde} ${madde === 1 ? "article" : "articles"}; everyone, the CEO included, follows it and machine rules are enforced at the gate.`,
    istenCikarma: (ad: string, devralan: string | null) => `${ad} leaves the team; their open work and knowledge go to ${devralan ?? "their manager"}.`,
    teslim: (ajan: string) => `The delivery is accepted and recorded in memory. If you reject it with a note, the note goes back to ${ajan} as work.`,
    sureli: "If time runs out, it's rejected automatically.",
  },

  fiil: {
    ise_alim: "Hire",
    birlestirme: "Merge",
    genel: "Approve",
    arac: "Allow",
    anayasa: "Enact",
    isten_cikarma: "Let go",
    teslim: "Accept",
  },
  notEkle: "Add note",
  notEtiketi: "Decision note (optional)",
  notYer: "Note (optional) · sent to the agent",
  kararBildirimi: (baslik: string, onaylandi: boolean) => `${baslik}: ${onaylandi ? "approved" : "rejected"}.`,
  denetimdeKararVer: "Decide in Audit",
  not: (not: string) => `Note: ${not}`,

  alan: {
    ad: "Name",
    aday: "Candidate",
    rol: "Role",
    model: "Model",
    yoneticiId: "Manager",
    yoneticiAd: "Manager",
    karakter: "Character",
    talimatEki: "Extra instructions",
    gerekce: "Reason",
    ajanId: "Agent",
    isteyenId: "Requested by",
    dalSahibi: "Branch owner",
    gorevId: "Task",
    dal: "Branch",
    hedefDal: "Target branch",
    degisiklik: "Changes",
    dosyaSayisi: "Files",
    eklenen: "Lines added",
    silinen: "Lines removed",
    testler: "Tests",
    ozet: "Summary",
    soru: "Question",
    secenekler: "Options",
    arac: "Tool",
    komut: "Command",
    girdi: "Input",
    kural: "Rule",
    aracKimligi: "Call ID",
  },
  dosya: (n: number) => `${n} ${n === 1 ? "file" : "files"}`,
  rolVarsayilani: "role default",
  karakterOtomatik: "Automatic · picked by role",
  secenekIpucu: "Write your pick in the note; it goes to the agent as the answer.",
};
