// Onaylar (İngilizce)
import type { onaylar as tr } from "../tr/onaylar";

export const onaylar: typeof tr = {
  baslik: "Approvals",
  altBaslik: "Hiring, merges into main and irreversible decisions go through you",
  tureGore: "Filter by type",
  butunTurler: "All types",
  durum: {
    bekliyor: "Pending",
    onaylandi: "Approved",
    reddedildi: "Rejected",
    zaman_asimi: "Expired",
  },
  alinamadi: "Couldn't load approvals.",

  bekleyenler: "Pending decisions",
  bekleyenYok: "No pending decisions",
  bekleyenYokMetin: "When the CEO proposes a hire or a piece of work is ready to go into main, you decide here.",
  turdeBekleyenYok: "No pending decisions of this type",

  gecmis: "History",
  sonucaGore: "Filter by outcome",
  gecmisYok: "Nothing decided yet",
  gecmisYokMetin: "Your decisions collect here, along with your notes.",
  suzgecteYok: "Nothing matches this filter",
  suzgeciDegistirin: "Change the filter.",
  dahaGoster: (n: number) => `Show ${n} more`,

  kim: {
    ise_alim: "Proposed by",
    birlestirme: "Requested by",
    genel: "Asked by",
    arac: "Requested by",
    anayasa: "Proposed by",
    isten_cikarma: "Proposed by",
    teslim: "Delivered by",
  },
  bilinmeyenAjan: "Unknown agent",
  oturumunuAc: (ad: string) => `Open ${ad}'s session`,
  sureYok: "No deadline",
  kaldi: (sure: string) => `${sure} left`,
  sureDoldu: "Time's up · will be rejected",
  sureIpucu: "Rejected automatically when time runs out",

  sonra: {
    ise_alim: "If approved",
    birlestirme: "If approved",
    genel: "If approved",
    arac: "If allowed",
    anayasa: "If approved",
    isten_cikarma: "If approved",
    teslim: "If accepted",
  },
  etki: {
    iseAlim: (ad: string, rol: string, yonetici: string | null) =>
      `${ad} joins the team as ${rol} and reports to ${yonetici ?? "the board directly"}; a workspace is set up for them.`,
    genel: (ajan: string) => `${ajan} gets your decision and goes ahead accordingly; your note is passed on as the answer.`,
    arac: (ajan: string, arac: string) => `${ajan} runs this ${arac} call.`,
    anayasa: (madde: number) => `The constitution takes effect with ${madde} ${madde === 1 ? "article" : "articles"}; everyone, the CEO included, follows it and machine rules are enforced at the gate.`,
    istenCikarma: (ad: string, devralan: string | null) => `${ad} leaves the team; their open work and knowledge go to ${devralan ?? "their manager"}.`,
    teslim: (ajan: string) => `The delivery is accepted and recorded in memory. If you reject it with a note, the note goes back to ${ajan} as work.`,
    sureli: "If time runs out, it's rejected automatically.",
  },

  fiil: {
    ise_alim: "Hire",
    birlestirme: "Merge",
    genel: "Approve",
    arac: "Allow",
    anayasa: "Enact",
    isten_cikarma: "Let go",
    teslim: "Accept",
  },
  notEkle: "Add note",
  notEtiketi: "Decision note (optional)",
  notYer: "Note (optional) · sent to the agent",
  kararBildirimi: (baslik: string, onaylandi: boolean) => `${baslik}: ${onaylandi ? "approved" : "rejected"}.`,
  denetimdeKararVer: "Decide in Audit",
  not: (not: string) => `Note: ${not}`,

  alan: {
    ad: "Name",
    aday: "Candidate",
    rol: "Role",
    model: "Model",
    yoneticiId: "Manager",
    yoneticiAd: "Manager",
    karakter: "Character",
    talimatEki: "Extra instructions",
    gerekce: "Reason",
    ajanId: "Agent",
    isteyenId: "Requested by",
    dalSahibi: "Branch owner",
    gorevId: "Task",
    dal: "Branch",
    hedefDal: "Target branch",
    degisiklik: "Changes",
    dosyaSayisi: "Files",
    eklenen: "Lines added",
    silinen: "Lines removed",
    testler: "Tests",
    ozet: "Summary",
    soru: "Question",
    secenekler: "Options",
    arac: "Tool",
    komut: "Command",
    girdi: "Input",
    kural: "Rule",
    aracKimligi: "Call ID",
    maddeler: "Articles",
    ayrilan: "Leaving",
    devralanId: "Takes over",
    testAdimlari: "Test steps",
    calistir: "Run",
    adres: "Address",
    baslik: "Title",
  },
  dosya: (n: number) => `${n} ${n === 1 ? "file" : "files"}`,
  rolVarsayilani: "role default",
  karakterOtomatik: "Automatic · picked by role",
  secenekIpucu: "Write your pick in the note; it goes to the agent as the answer.",

  anayasa: {
    kural: "Machine rule",
    hedefEtiketi: "Target",
    hedef: { komut: "Command", yol: "File path", url: "URL", arac: "Tool" },
    desen: (n: number) => (n === 1 ? "Pattern" : "Patterns"),
    kararEtiketi: "Decision",
    karar: { ret: "Rejected", sor: "Asks the board" },
    yalnizTalimat: "Instruction only · no machine rule",
  },
  devralanYok: "Their manager takes over",

  oto: {
    etiket: "Auto-approve",
    ipucuKapali: (n: number) =>
      n
        ? `Tick it and ${n === 1 ? "the pending approval" : `the ${n} pending approvals`} in scope ${n === 1 ? "is" : "are"} granted right away.`
        : "Tick it and approvals in scope are granted automatically.",
    ipucuAcik: "Approvals in scope are granted automatically.",
    kapsam: "Scope",
    kapsamSayisi: (n: number, toplam: number) => `${n}/${toplam}`,
    kapsamEtiketi: "Types granted automatically",
    turAciklama: {
      arac: "Commands, file and network calls",
      ise_alim: "The CEO's hiring proposals",
      birlestirme: "Reviewed branches going into the working branch",
      genel: "Questions to the board",
      anayasa: "Constitution proposals",
      isten_cikarma: "Proposals to let someone go",
      teslim: "Accepting finished work",
    },
    aciklama: "Merges, questions and deliveries need your decision, so they're out of scope by default.",
    varsayilan: "Reset to default",
    uyari: (turler: string) => `Auto-approve is on: ${turler} approvals are granted automatically. Each one is recorded in History.`,
    uyariBos: "Auto-approve is on, but the scope is empty; nothing is granted automatically.",
    kapat: "Turn off auto-approve",
    acildi: (n: number) =>
      n
        ? `Auto-approve is on. ${n === 1 ? "The pending approval" : `${n} pending approvals`} in scope ${n === 1 ? "is" : "are"} being granted now.`
        : "Auto-approve is on. New approvals in scope will be granted automatically.",
    kapandi: "Auto-approve is off. Approvals wait for you again.",
    kapsamGuncellendi: "Auto-approve scope updated.",
  },
};
