// Projeler (İngilizce)
import type { projeler as tr } from "../tr/projeler";

export const projeler: typeof tr = {
  baslik: "Projects",
  aciklama: "Each project is a git repository with its own team, board, memory and audit policy",
  yeniProje: "New project",
  githubdanAc: "Open from GitHub",
  klasorBagla: "Connect folder",
  listeAlinamadi: "Couldn't load the project list.",
  acikProjeler: "Open projects",
  ekip: "Team",
  onay: "Approvals",
  bugun: "Today",
  bugunBaslik: "Tokens processed today",
  karargahaGit: "Go to Headquarters",
  listedenCikar: "Remove from list",
  cikarEtiket: (ad: string) => `Remove ${ad} from the list`,
  cikarOnay: (ad: string) =>
    `${ad} will be removed from the ArnOrg list. The repo, the .arnorg/ folder and the workspaces stay on disk; you can connect the same path again.`,
  cikarildi: (ad: string) => `${ad} was removed from the list. Its files were not touched.`,
  form: {
    ilkBaslik: "Open your first project",
    baslik: "Open a project",
    kapat: "Close form",
    ilkAciklamaOnce: "A project is a git repository that ArnOrg manages. Opening one adds a ",
    ilkAciklamaSonra:
      " scaffold to the repo (vision and architecture notes, team identities, memory) and hires a CEO agent. You give the brief; the CEO drafts the plan, proposes the team and hands out the work.",
  },
  ayar: {
    ac: "Project settings",
    acEtiket: (ad: string) => `Settings for ${ad}`,
    dal: "Working branch",
    dalIpucu: "Agents branch off it, and approved merges go into it.",
    dalDegistir: "Change branch",
    dalDegisti: (dal: string) => `The working branch is now ${dal}.`,
    dallarAlinamadi: "Couldn't load branches",
    dalFarkli: (mevcut: string, calisma: string) => `The main repo is on ${mevcut}; the working branch is ${calisma}.`,
    uzak: "Remote",
    uzakYok: "This project has no remote.",
    esitle: "Sync now",
    gonder: "Push now",
    bekleyen: (n: number) => (n === 1 ? "1 commit waiting to be pushed." : `${n} commits waiting to be pushed.`),
    sonEsitleme: (zaman: string) => `Last synced ${zaman}`,
    githubAc: "Create GitHub repository",
    githubAcIpucu: "Creates the repository, pushes the working branch and sets it as origin.",
    githubAcildi: (depo: string) => `GitHub repository created: ${depo}.`,
    githubBagliDegil: "GitHub isn't connected; connect it first to create a repository.",
    githubBagla: "Connect in Settings",
    gonderim: "Pushing",
    otomatikGonder: "Push to the remote after approved merges",
    otomatikGonderIpucu: "When off, approved work only goes into the working branch on this computer.",
    otomatikGonderUzakYok: "Takes effect once a remote is connected.",
    otomatikAcik: "Approved merges will also be pushed to the remote.",
    otomatikKapali: "Approved merges will stay on this computer.",
  },
};
