// Skills (English): ArnOrg's Claude Code skill library; the picker in the hire form and the section in the employee panel
import type { SkillKategorisi } from "@arnorg/ortak";
import type { skiller as tr } from "../tr/skiller";

export const skiller: typeof tr = {
  baslik: "Skills",
  sayac: (n: number) => `${n} ${n === 1 ? "skill" : "skills"}`,
  ipucu: "Claude Code skills from ArnOrg's library, loaded into the employee's sessions; changes arrive in the next session. The methods the team has learned are on the Intelligence tab.",
  iseAlimIpucu: "Starts with the role's defaults; add the ones that fit the work and remove the rest. Skills are loaded into the employee's sessions.",
  ceo: "The CEO does not use skills; they assign skills to the people they hire.",
  bos: "No skills assigned.",
  ekle: "Add skill",
  listeyiKapat: "Close the list",
  ara: "Search skills",
  araYer: "Name, id or topic",
  roleUyan: "Fit this role",
  tumu: "All",
  suzgec: "Skills shown",
  sonucYok: "No skill matches the search.",
  hepsiAtanmis: "Every skill in this list is assigned.",
  varsayilan: "Role default",
  varsayilanaDon: "Back to role defaults",
  cikar: (ad: string) => `Remove: ${ad}`,
  ekleEtiket: (ad: string) => `Add: ${ad}`,
  eklendi: (ajan: string, ad: string) => `${ajan}: added ${ad}.`,
  cikarildi: (ajan: string, ad: string) => `${ajan}: removed ${ad}.`,
  varsayilanaDondu: (ajan: string) => `${ajan} is back to the role's default skills.`,
  yukleniyor: "Loading the skill library",
  alinamadi: "Couldn't load the skill library.",
  yenidenDene: "Try again",
  kaynak: (depo: string, lisans: string) => `${depo} · ${lisans}`,
  kategoriler: {
    muhendislik: "Engineering",
    test: "Testing",
    inceleme: "Code review",
    backend: "Backend",
    veri: "Data",
    mimari: "Architecture",
    frontend: "Frontend",
    tasarim: "Design",
    guvenlik: "Security",
    devops: "DevOps",
    yazim: "Technical writing",
    arastirma: "Research",
    tanitim: "Product marketing",
  } as Record<SkillKategorisi, string>,
};
