// Browser screen: in-app browser, correction notes by picking an element, notes panel (English)
import type { tarayici as tr } from "../tr/tarayici";

export const tarayici: typeof tr = {
  baslik: "Browser",
  bolumEtiketi: "In-app browser",
  arac: {
    etiket: "Browser toolbar",
    geri: "Back",
    ileri: "Forward",
    yenile: "Reload",
    durdur: "Stop",
    adres: "Address",
    adresIpucu: "Type an address or search",
    adresBaslik: (kisayol: string) => `Address or search (${kisayol})`,
    git: "Go",
    sec: "Pick element",
    secBaslik: (kisayol: string) => `Click an element on the page and leave a note (${kisayol}) · Esc to exit`,
    genislik: "Viewport width",
    masaustu: "Desktop",
    tablet: "Tablet 768",
    telefon: "Phone 390",
  },
  secimIpucu: "Pick element · click what's wrong · Esc to exit",
  yukleniyor: "Page loading",
  kare: "Snapshot of the page",
  boyut: (genislik: number, yukseklik: number) => `${genislik} × ${yukseklik}`,
  yonerge: {
    baslik: "Open your project's running page",
    adim1: "Click one of the Links, or type the page's address in the address bar, e.g. localhost:5173.",
    adim2: "Press Pick element and click whatever isn't right.",
    adim3: "Write what's wrong. Notes pile up on the side; Get it all done sends them all to the CEO as work.",
    kisayollar: (adres: string, sec: string) => `${adres} address · ${sec} pick element · Esc leave the picker`,
    hizli: "Local addresses",
    linkler: "Project links",
  },
  hata: {
    baslik: "The page could not be opened",
    ipucu: "Is the server running? Check the address and try again.",
  },
  web: {
    baslik: "The in-app browser runs in the desktop app",
    metin:
      "In the desktop app the page opens right here: you click an element and leave your note, and its selector, text and a screenshot are attached on their own. Here, add the note by hand: the page's address and what's wrong are enough.",
    formBaslik: "Manual note",
    adres: "Page address",
    adresIpucu: "localhost:5173/cart",
    adresHata: "Enter a valid address, e.g. localhost:5173/cart or https://example.com.",
    not: "Note",
    ekle: "Add note",
  },
  not: {
    baslik: "Correction note",
    etiket: "What's wrong?",
    ipucu: "This isn't right: …",
    secici: "Selector",
    metin: "Element text",
    sayfa: "Page",
    gorunum: "Viewport",
    gorselAlt: "Screenshot of the picked element",
    gorselYok: "The screenshot could not be taken; the selector and element text are still attached.",
    kaydet: "Save",
    kaydetVeSec: "Save, pick another",
    kisayol: (kaydet: string) => `${kaydet} saves · Esc cancels`,
  },
  panel: {
    baslik: "Notes",
    sayac: (n: number) => `${n} open`,
    ac: "Show notes",
    kapat: "Hide notes",
    bosBaslik: "No notes yet",
    bosMasaustu: "Press Pick element, click an element on the page and write what's wrong.",
    bosWeb: "Use the form to add the page's address and your note; notes pile up here.",
    elle: "Added by hand",
    sayfayaGit: (adres: string) => `Open ${adres}`,
    duzenle: "Edit note",
    sil: "Delete note",
    silOnay: "Delete this note? Its screenshot is deleted too.",
    silOnayGonderilmis: "Remove this note from the list? The screenshot the CEO received stays in place.",
    hepsiniYaptir: "Get it all done",
    hepsiniYaptirAlt: "Open notes go to the CEO in one message; the CEO opens and assigns a task for each.",
    gonderOnay: (n: number) =>
      `${n === 1 ? "1 note goes" : `${n} notes go`} to the CEO, who will open a task with acceptance criteria for each and assign it to the right employee. Send?`,
    gonder: "Send",
    gonderildi: (n: number) => (n === 1 ? "1 note went to the CEO." : `${n} notes went to the CEO.`),
    karargahIpucu: "The CEO's reply and the tasks it opens show up in Headquarters.",
    karargahaGec: "Go to Headquarters",
    gonderilenler: (n: number) => `Sent · ${n}`,
    gonderimZamani: (zaman: string) => `sent ${zaman}`,
  },
};
