// Zekâ ekranı: ana yasa, global zekâ, beceriler, sözler ve ajan zekâsı (İngilizce)
import type { AnayasaKurali, KuralDurumu, KuralKaynagi, SozDurumu, ZekaGunlukTuru } from "@arnorg/ortak";
import type { zeka as tr } from "../tr/zeka";

export const zeka: typeof tr = {
  altBaslik: "Everything your agents never forget: the project's constitution, ArnOrg's global intelligence, team skills and promises",
  bolumler: "Intelligence sections",
  sekme: {
    anayasa: "Constitution",
    kuresel: "Global intelligence",
    beceriler: "Skills",
    sozler: "Promises",
  },
  sekmeIpucu: {
    anayasa: "The project's binding rules; everyone follows them, the CEO included",
    kuresel: "Standards ArnOrg has learned across all projects",
    beceriler: "Methods the team has learned in this project",
    sozler: "Open promises employees made to each other and to the board",
  },

  anayasa: {
    yukleniyor: "Loading the constitution",
    alinamadi: "Couldn't load the constitution.",
    belgeAdi: (proje: string) => `${proje} constitution`,
    surum: (n: number) => `Version ${n}`,
    guncellendi: (zaman: string) => `Updated ${zaman}`,
    onaylayan: (kim: string) => `Approved by: ${kim}`,
    maddeSayisi: (n: number) => (n === 1 ? "1 article" : `${n} articles`),
    kapidaSayisi: (n: number) => `${n} enforced at the gate`,
    aciklama:
      "It sits at the very top of every agent's instructions, and everyone follows it, the CEO included. Articles with a machine rule are enforced at the audit gate: a matching command, file path or URL is stopped. When the constitution changes, the whole team is reminded.",
    maddeler: "Articles",
    kapi: "Audit gate",
    kapiIpucu: "This article is also enforced as a machine rule at the audit gate",
    kararSonuc: { ret: "blocked", sor: "asks the board" } as Record<AnayasaKurali["karar"], string>,
    desenler: "Patterns",
    oneriBekliyor: "The CEO's constitution proposal is waiting for your approval",
    oneriyiIncele: "Review in Approvals",
    bosBaslik: "This project has no constitution yet",
    bosMetin:
      "You write the constitution together with the CEO: start the kickoff in Headquarters or message the CEO. The CEO proposes the articles and you approve them. Approved articles go to the top of every agent's instructions, the CEO's included, and the whole project follows them.",
    karargah: "Prepare in Headquarters",
    ceoyaYaz: (ceo: string) => `Message ${ceo}`,
    kendimYazayim: "I'll write it myself",

    duzenBaslik: "Editing the constitution",
    duzenAciklama: (surum: number) =>
      `When you save, version ${surum} takes effect, the whole team is told, and every agent is reminded on their next turn.`,
    maddeEtiketi: (no: number) => `Article ${no}`,
    baslik: "Title",
    baslikOrnek: "E.g. Secrets",
    metin: "Text",
    metinOrnek: "E.g. .env files and keys are never read, committed or posted to channels.",
    kuralEkle: "Add a machine rule",
    kuralEkleIpucu: "Don't leave it as an instruction only; have the audit gate stop matching calls too",
    kuralBaslik: "Machine rule",
    kuralAciklama: "Checked first at the audit gate on every tool call.",
    kuralKaldir: "Remove rule",
    hedef: "What it checks",
    kararAdi: "On match",
    kararSecenek: { ret: "Block", sor: "Ask the board" } as Record<AnayasaKurali["karar"], string>,
    desenlerIpucu: "One regular expression per line; case-insensitive.",
    desenOrnek: "E.g. \\bgit\\s+push\\b",
    gecersizDesen: (neden: string) => `invalid regular expression${neden ? ` (${neden})` : ""}`,
    yukari: (no: number) => `Move article ${no} up`,
    asagi: (no: number) => `Move article ${no} down`,
    sil: (no: number) => `Delete article ${no}`,
    maddeEkle: "Add article",
    maddeSiniri: "The constitution can have at most 40 articles.",
    kaydet: "Save and put into effect",
    degisiklikYok: "No changes yet.",
    kaydedilmemis: "Unsaved changes",
    yururlukte: (surum: number) =>
      `Constitution version ${surum} is in effect. The whole team has been told; every agent will be reminded on their next turn.`,
    kaydedilemedi: "Couldn't save the constitution",
    vazgecSor: "Discard the changes in this draft?",
    vazgecEvet: "Yes, discard the draft",
    surumDegisti: (surum: number) =>
      `The constitution was updated while you were editing (version ${surum}). If you save, this draft replaces it.`,
    yeniSurumdenBasla: "Start over from the new version",
    hata: {
      baslik: "A title is required.",
      metin: "Text is required.",
      desenYok: "Add at least one pattern or remove the machine rule.",
      maddeYok: "At least one article is required.",
      ozet: (n: number) => (n === 1 ? "1 article needs fixing" : `${n} articles need fixing`),
    },
  },

  kuresel: {
    aciklama:
      "Standards ArnOrg has learned across all your projects. Each agent receives them within its role and authority, and the set keeps improving itself: the board's preferences, lessons and corrections become rules automatically; a candidate seen in another project becomes a standard; duplicates merge and weak rules retire.",
    yukleniyor: "Loading global intelligence",
    alinamadi: "Couldn't load global intelligence.",
    durumAdi: { etkin: "Standard", aday: "Candidate", emekli: "Retired" } as Record<KuralDurumu, string>,
    grupBaslik: { etkin: "Standards", aday: "Candidates", emekli: "Retired" } as Record<KuralDurumu, string>,
    grupAciklama: {
      etkin: "Given to every agent within its scope.",
      aday: "Becomes a standard once it shows up in another project or its confidence reaches 65%.",
      emekli: "No longer given to agents: it weakened, was merged, or the board retired it.",
    } as Record<KuralDurumu, string>,
    ozetEtiketi: "Rule counts; select one to filter by status",
    duruma: (durum: string, n: number) => `${durum}: ${n === 1 ? "1 rule" : `${n} rules`}. Show only these`,
    sonOgrenme: "Last learned",
    henuzOgrenmedi: "Nothing yet",
    kapsamSuzgeci: "Filter by scope",
    tumKapsamlar: "All scopes",
    araEtiket: "Search rules",
    araYer: "Search: commit, test, schema…",
    kuralEkle: "Add rule",
    suzgecleriTemizle: "Clear filters",
    sonuc: (n: number) => (n === 1 ? "1 rule" : `${n} rules`),
    eslesenYok: "No matching rules",
    eslesenYokMetin: "Loosen the filters or change the search.",
    grupBos: "No rules in this group.",
    bosBaslik: "Global intelligence is empty for now",
    bosMetin:
      "The board's general preferences, agents' lessons and corrections turn into rules here. You can also write the first rule yourself; it becomes a standard in every project.",
    ilkKural: "Write the first rule",

    kapsam: { herkes: "Everyone", yonetici: "Managers", gelistirici: "Developers" },
    kapsamEtiketi: "Who gets it",
    kapsamIpucu: "If nothing is selected, everyone gets it. Managers covers manager roles such as the CEO; developers covers every other role.",
    kaynak: {
      kurul: "Board",
      tercih: "Board preference",
      ogrenilen: "Lesson",
      duzeltme: "Correction",
      ajan: "Agent suggestion",
    } as Record<KuralKaynagi, string>,
    kaynakIpucu: "Where the rule was learned",

    guven: "confidence",
    guvenIpucu:
      "Confidence grows with evidence and positive feedback, and drops when the rule is reported wrong. A candidate becomes a standard at 65%; a rule that falls below 30% retires.",
    esikStandart: "Standard threshold 65%",
    esikEmekli: "Retirement threshold 30%",
    kanit: "Evidence",
    kanitIpucu: "Observations that back the rule; show or hide",
    kullanim: "Uses",
    kullanimIpucu: "Sessions in which the rule was part of an agent's instructions",
    yarar: "Helped",
    yararIpucu: "Times it was reported helpful",
    ihlal: "Broken",
    ihlalIpucu: "Times it was broken",
    kurulKaniti: "Board",
    guncellendi: (zaman: string) => `Updated ${zaman}`,
    kanitlarEtiketi: "Evidence",

    eylemler: "Rule actions",
    iseYaradi: "Helped",
    iseYaradiIpucu: "This rule helped: its confidence goes up",
    yanlis: "Wrong",
    yanlisIpucu: "This rule is wrong or harmful: its confidence drops, and it retires below 30%",
    durumaAl: { etkin: "Make standard", aday: "Back to candidate", emekli: "Retire" } as Record<KuralDurumu, string>,
    duzenleEtiketi: (kisa: string) => `Edit rule: ${kisa}`,
    silEtiketi: (kisa: string) => `Delete rule: ${kisa}`,
    silUyari:
      "This rule is deleted permanently from every project. To keep it with its evidence, retire it instead; retired rules aren't given to agents.",
    silindi: "Rule deleted.",
    durumBildirimi: {
      etkin: "The rule is now a standard; agents in its scope get it in every project.",
      aday: "The rule is back to candidate; it will gather evidence again.",
      emekli: "The rule is retired; agents won't get it anymore.",
    } as Record<KuralDurumu, string>,
    geriBildirimAlindi: (guven: string) => `Feedback saved. Confidence is now ${guven}.`,
    emekliyeAyrildi: "Its confidence fell below 30%; the rule retired.",
    vurgulandi: "Rule highlighted",

    form: {
      yeniEtiketi: "New global rule",
      duzenleEtiketi: "Edit global rule",
      metin: "Rule",
      metinOrnek: "E.g. Check a dependency's license and last update before adding it.",
      sayac: (n: number) => `${n} / 600`,
      kisa: "A rule needs at least 5 characters.",
      kurulKurali: "A rule the board writes becomes a standard right away and goes to agents in the selected scope in every project.",
      ekle: "Add rule",
      eklendi: "Rule added; it's a standard in every project.",
      guncellendi: "Rule updated.",
    },

    gunluk: {
      baslik: "Learning log",
      etiket: "Learning log, newest first",
      canli: "Live",
      kopuk: "Offline",
      tur: {
        ogrendi: "Learned",
        guclendi: "Strengthened",
        etkinlesti: "Became a standard",
        birlestirdi: "Merged",
        emekli: "Retired",
        duzenlendi: "Edited",
        geri_bildirim: "Feedback",
        eledi: "Project-specific, skipped",
      } satisfies Record<ZekaGunlukTuru, string>,
      bos: "Nothing learned yet. Entries appear here as the board shares preferences and agents draw lessons.",
      dahaEski: (n: number) => (n === 1 ? "Show 1 older entry" : `Show ${n} older entries`),
      kurala: (kisa: string) => `Go to rule: ${kisa}`,
    },
  },

  beceriler: {
    aciklama:
      "Methods the team has learned in this project. Agents see the skill index in their instructions and read the full text when they need it; an agent that reuses a method that worked writes it down as a skill.",
    yukleniyor: "Loading skills",
    alinamadi: "Couldn't load skills.",
    icerikAlinamadi: "Couldn't read the skill.",
    icerikYukleniyor: "Loading the skill",
    bosBaslik: "No skills yet",
    bosMetin: "When an agent reuses a method that worked, it writes it down as a skill, and the team follows the same path next time.",
    yazan: (ad: string) => `Written by ${ad}`,
    kullanim: (n: number) => (n === 0 ? "Not used yet" : n === 1 ? "Used once" : `Used ${n} times`),
    guncellendi: (zaman: string) => `Updated ${zaman}`,
    kullanimNotu: "Reading a skill counts as a use.",
  },

  sozler: {
    aciklama:
      "Promises employees made to each other and to the board. Until an open promise is kept, both the person who made it and the one it was made to are reminded every turn.",
    yukleniyor: "Loading promises",
    alinamadi: "Couldn't load promises.",
    acik: "Open promises",
    kapanan: "Closed",
    bosBaslik: "No promises yet",
    bosMetin: "When an agent promises work to a teammate or to the board, it shows up here, and both sides are reminded until it's kept.",
    acikYok: "No open promises; every promise made has been closed.",
    durum: { acik: "Open", tutuldu: "Kept", iptal: "Cancelled" } as Record<SozDurumu, string>,
    sonTarih: "Due",
    sonTarihYok: "No due date",
    gecikti: (goreli: string) => `overdue · ${goreli}`,
    verildi: (zaman: string) => `Made ${zaman}`,
    kapandi: (zaman: string) => `Closed ${zaman}`,
    kime: (veren: string, alan: string) => `${veren} promised ${alan}`,
    not: "Note",
  },

  ajan: {
    aciklama: "Their own lasting intelligence: they don't forget who they are, the work they were given or the promises they made.",
    yukleniyor: "Loading their intelligence",
    alinamadi: "Couldn't load the agent's intelligence.",
    kisisel: "Personal memory",
    kisiselKullanim: (kullanilan: string, sinir: string) => `${kullanilan} / ${sinir} characters`,
    kisiselIpucu: "Goes into their instructions as a frozen snapshot when a session starts; changes made during a session apply from the next one.",
    kisiselBos: "No personal memory yet. As they work, they note here what matters to them.",
    kisiselDolu: "Close to the limit; the agent will merge similar entries.",
    baglar: "Team ties",
    baglarIpucu: "Ties that go into their instructions every turn; hooks remind them of these from time to time while they work.",
    baglarBos: "No ties yet.",
    verdigi: "Promises they made",
    aldigi: "Promises made to them",
    sozYok: "None.",
    defter: "Journal",
    defterIpucu: "Work notes they write at the end of each turn; edit them in the Journals section of the Memory screen.",
    defterBos: "The journal is empty.",
    tamaminiGoster: "Show all",
    kisalt: "Show less",
    beceriler: "Team skills they know",
    beceriAc: (ad: string) => `Open the ${ad} skill on the Intelligence screen`,
    aktar: "Transfer memory",
    aktarAciklama:
      "So nothing is lost in a handover: their personal memory and journal are written into the chosen employee's journal as a “Handover” section, and a short note goes into that employee's personal memory. Their own memory stays as it is.",
    aktarAc: "Transfer memory…",
    kime: "To",
    yoneticisi: "their manager",
    not: "Note (optional)",
    notOrnek: "E.g. The rest of T-24 is yours; watch the shipping API's timeouts.",
    sozleriDevret: "Hand over their open promises too",
    sozleriDevretIpucu: (n: number) =>
      n === 0 ? "They have no open promises right now." : n === 1 ? "1 open promise is made again in the new owner's name." : `${n} open promises are made again in the new owner's name.`,
    aktarDugme: "Transfer",
    kimseYok: "There's no one else to transfer to.",
  },
};
