// FY Mürekkep: VS Code tezgâhının varsayılan koyu teması. Stüdyo tokenlarından (stiller/tokenlar.css) türetilir:
// mürekkep zemin, kâğıt metin, tek mercan vurgu, gölgesiz, kıl çizgiler.

export const TEMA_ADI = "FY Mürekkep";

/** oklch(0.72 0.19 25) sRGB karşılığı (kırpılmış) */
const MERCAN = "#ff6a65";
/** oklch(0.78 0.16 28) */
const MERCAN_ACIK = "#ff8b7c";

const R = {
  murekkep: "#0a0a0b",
  murekkep2: "#0f0f11",
  murekkep3: "#161619",
  murekkep4: "#222226",
  murekkep5: "#2e2e33",
  kagit: "#f2f0ec",
  kemik: "#ede7dc",
  sonuk: "#a19c94",
  sonuk2: "#77726b",
  cizgiYumusak: "#f2f0ec0f",
  cizgi: "#f2f0ec1a",
  cizgiGuclu: "#f2f0ec38",
  tamam: "#7ad59c",
  uyari: "#f1c45e",
  sil: "#fb817f",
  dize: "#aed59a",
  tur: "#95cde9",
  etiket: "#eeae7b",
  sayi: "#eccb72",
  yok: "#00000000",
};

const renkler: Record<string, string> = {
  // genel
  foreground: R.kagit,
  descriptionForeground: R.sonuk,
  disabledForeground: R.sonuk2,
  errorForeground: R.sil,
  focusBorder: `${MERCAN}99`,
  contrastBorder: R.yok,
  "widget.border": R.cizgi,
  "widget.shadow": R.yok,
  "scrollbar.shadow": R.yok,
  "selection.background": `${MERCAN}55`,
  "icon.foreground": R.sonuk,
  "sash.hoverBorder": `${MERCAN}aa`,
  "progressBar.background": MERCAN,
  "textLink.foreground": MERCAN_ACIK,
  "textLink.activeForeground": MERCAN,
  "textPreformat.foreground": R.etiket,
  "textBlockQuote.background": R.murekkep2,
  "textBlockQuote.border": R.cizgiGuclu,
  "textCodeBlock.background": R.murekkep3,
  "textSeparator.foreground": R.cizgi,

  // düğme, rozet, girdi
  "button.background": MERCAN,
  "button.foreground": R.murekkep,
  "button.hoverBackground": MERCAN_ACIK,
  "button.border": R.yok,
  "button.separator": `${R.murekkep}66`,
  "button.secondaryBackground": R.murekkep4,
  "button.secondaryForeground": R.kagit,
  "button.secondaryHoverBackground": R.murekkep5,
  "badge.background": MERCAN,
  "badge.foreground": R.murekkep,
  "activityBarBadge.background": MERCAN,
  "activityBarBadge.foreground": R.murekkep,
  "input.background": R.murekkep3,
  "input.foreground": R.kagit,
  "input.border": R.cizgi,
  "input.placeholderForeground": R.sonuk2,
  "inputOption.activeBorder": MERCAN,
  "inputOption.activeBackground": `${MERCAN}26`,
  "inputOption.activeForeground": R.kagit,
  "inputValidation.errorBackground": "#2a1514",
  "inputValidation.errorBorder": R.sil,
  "inputValidation.warningBackground": "#2a2414",
  "inputValidation.warningBorder": R.uyari,
  "inputValidation.infoBackground": R.murekkep3,
  "inputValidation.infoBorder": R.tur,
  "dropdown.background": R.murekkep3,
  "dropdown.listBackground": R.murekkep2,
  "dropdown.border": R.cizgi,
  "dropdown.foreground": R.kagit,
  "checkbox.background": R.murekkep3,
  "checkbox.border": R.cizgiGuclu,
  "checkbox.foreground": R.kagit,
  "keybindingLabel.background": R.murekkep3,
  "keybindingLabel.foreground": R.kemik,
  "keybindingLabel.border": R.cizgi,
  "keybindingLabel.bottomBorder": R.cizgi,

  // listeler ve ağaçlar
  "list.activeSelectionBackground": R.murekkep4,
  "list.activeSelectionForeground": R.kagit,
  "list.activeSelectionIconForeground": R.kagit,
  "list.inactiveSelectionBackground": R.murekkep3,
  "list.inactiveSelectionForeground": R.kagit,
  "list.hoverBackground": R.murekkep3,
  "list.hoverForeground": R.kagit,
  "list.focusBackground": R.murekkep4,
  "list.focusOutline": `${MERCAN}80`,
  "list.inactiveFocusOutline": R.yok,
  "list.highlightForeground": MERCAN_ACIK,
  "list.focusHighlightForeground": MERCAN_ACIK,
  "list.dropBackground": `${MERCAN}22`,
  "list.errorForeground": R.sil,
  "list.warningForeground": R.uyari,
  "listFilterWidget.background": R.murekkep3,
  "listFilterWidget.outline": MERCAN,
  "listFilterWidget.noMatchesOutline": R.sil,
  "tree.indentGuidesStroke": R.cizgi,
  "tree.inactiveIndentGuidesStroke": R.cizgiYumusak,

  // etkinlik çubuğu ve yan çubuk
  "activityBar.background": R.murekkep,
  "activityBar.foreground": R.kagit,
  "activityBar.inactiveForeground": R.sonuk2,
  "activityBar.border": R.cizgi,
  "activityBar.activeBorder": MERCAN,
  "activityBar.activeBackground": R.yok,
  "activityBar.activeFocusBorder": MERCAN,
  "activityBarTop.foreground": R.kagit,
  "activityBarTop.inactiveForeground": R.sonuk2,
  "activityBarTop.activeBorder": MERCAN,
  "sideBar.background": R.murekkep2,
  "sideBar.foreground": R.kemik,
  "sideBar.border": R.cizgi,
  "sideBarTitle.foreground": R.sonuk,
  "sideBarSectionHeader.background": R.murekkep2,
  "sideBarSectionHeader.foreground": R.sonuk,
  "sideBarSectionHeader.border": R.cizgi,
  "sideBarActivityBarTop.border": R.cizgi,
  "sideBarStickyScroll.background": R.murekkep2,
  "sideBarStickyScroll.border": R.cizgi,
  "sideBarStickyScroll.shadow": R.yok,

  // düzenleyici grupları ve sekmeler
  "editorGroup.border": R.cizgi,
  "editorGroup.dropBackground": `${MERCAN}1a`,
  "editorGroupHeader.tabsBackground": R.murekkep2,
  "editorGroupHeader.tabsBorder": R.cizgi,
  "editorGroupHeader.noTabsBackground": R.murekkep2,
  "editorGroupHeader.border": R.cizgi,
  "tab.activeBackground": R.murekkep,
  "tab.activeForeground": R.kagit,
  "tab.activeBorder": R.murekkep,
  "tab.activeBorderTop": MERCAN,
  "tab.inactiveBackground": R.murekkep2,
  "tab.inactiveForeground": R.sonuk,
  "tab.unfocusedActiveForeground": R.kemik,
  "tab.unfocusedActiveBorderTop": `${MERCAN}66`,
  "tab.unfocusedInactiveForeground": R.sonuk2,
  "tab.border": R.cizgi,
  "tab.hoverBackground": R.murekkep3,
  "tab.lastPinnedBorder": R.cizgiGuclu,
  "tab.dragAndDropBorder": MERCAN,
  "breadcrumb.background": R.murekkep,
  "breadcrumb.foreground": R.sonuk,
  "breadcrumb.focusForeground": R.kagit,
  "breadcrumb.activeSelectionForeground": R.kagit,
  "breadcrumbPicker.background": R.murekkep2,

  // düzenleyici
  "editor.background": R.murekkep,
  "editor.foreground": R.kagit,
  "editorLineNumber.foreground": "#4d4a46",
  "editorLineNumber.activeForeground": R.sonuk,
  "editorCursor.foreground": MERCAN,
  "editor.lineHighlightBackground": "#f2f0ec08",
  "editor.lineHighlightBorder": R.yok,
  "editor.selectionBackground": `${MERCAN}40`,
  "editor.inactiveSelectionBackground": `${MERCAN}22`,
  "editor.selectionHighlightBackground": "#f2f0ec12",
  "editor.wordHighlightBackground": "#f2f0ec10",
  "editor.wordHighlightStrongBackground": "#f2f0ec1a",
  "editor.findMatchBackground": `${R.sayi}55`,
  "editor.findMatchHighlightBackground": `${R.sayi}28`,
  "editor.findRangeHighlightBackground": "#f2f0ec0a",
  "editor.rangeHighlightBackground": "#f2f0ec0a",
  "editor.hoverHighlightBackground": "#f2f0ec10",
  "editorIndentGuide.background1": "#f2f0ec10",
  "editorIndentGuide.activeBackground1": "#f2f0ec30",
  "editorWhitespace.foreground": "#f2f0ec18",
  "editorRuler.foreground": R.cizgi,
  "editorBracketMatch.background": `${MERCAN}22`,
  "editorBracketMatch.border": `${MERCAN}80`,
  "editorBracketHighlight.foreground1": R.kemik,
  "editorBracketHighlight.foreground2": R.tur,
  "editorBracketHighlight.foreground3": R.etiket,
  "editorBracketHighlight.foreground4": R.dize,
  "editorBracketHighlight.foreground5": R.sayi,
  "editorBracketHighlight.foreground6": MERCAN_ACIK,
  "editorError.foreground": R.sil,
  "editorWarning.foreground": R.uyari,
  "editorInfo.foreground": R.tur,
  "editorHint.foreground": R.sonuk,
  "editorGutter.background": R.murekkep,
  "editorGutter.modifiedBackground": R.uyari,
  "editorGutter.addedBackground": R.tamam,
  "editorGutter.deletedBackground": R.sil,
  "editorOverviewRuler.border": R.yok,
  "editorOverviewRuler.modifiedForeground": `${R.uyari}99`,
  "editorOverviewRuler.addedForeground": `${R.tamam}99`,
  "editorOverviewRuler.deletedForeground": `${R.sil}99`,
  "editorOverviewRuler.errorForeground": R.sil,
  "editorOverviewRuler.warningForeground": R.uyari,
  "editorWidget.background": R.murekkep2,
  "editorWidget.foreground": R.kagit,
  "editorWidget.border": R.cizgiGuclu,
  "editorWidget.resizeBorder": MERCAN,
  "editorSuggestWidget.background": R.murekkep2,
  "editorSuggestWidget.border": R.cizgiGuclu,
  "editorSuggestWidget.selectedBackground": R.murekkep4,
  "editorSuggestWidget.highlightForeground": MERCAN_ACIK,
  "editorSuggestWidget.focusHighlightForeground": MERCAN_ACIK,
  "editorHoverWidget.background": R.murekkep2,
  "editorHoverWidget.border": R.cizgiGuclu,
  "editorHoverWidget.statusBarBackground": R.murekkep3,
  "editorStickyScroll.background": R.murekkep2,
  "editorStickyScroll.border": R.cizgi,
  "editorStickyScroll.shadow": R.yok,
  "editorStickyScrollHover.background": R.murekkep3,
  "editorCodeLens.foreground": R.sonuk2,
  "editorLink.activeForeground": MERCAN_ACIK,
  "editorInlayHint.background": R.murekkep3,
  "editorInlayHint.foreground": R.sonuk,
  "editorGhostText.foreground": R.sonuk2,
  "editorUnnecessaryCode.opacity": "#000000aa",
  "minimap.background": R.murekkep,
  "minimap.selectionHighlight": `${MERCAN}66`,
  "minimap.findMatchHighlight": `${R.sayi}88`,
  "minimapSlider.background": "#f2f0ec10",
  "minimapSlider.hoverBackground": "#f2f0ec1a",
  "minimapSlider.activeBackground": "#f2f0ec24",
  "minimapGutter.modifiedBackground": R.uyari,
  "minimapGutter.addedBackground": R.tamam,
  "minimapGutter.deletedBackground": R.sil,
  "scrollbarSlider.background": "#2e2e3399",
  "scrollbarSlider.hoverBackground": "#77726b99",
  "scrollbarSlider.activeBackground": "#a19c9499",

  // fark düzenleyici
  "diffEditor.insertedTextBackground": "#7ad59c22",
  "diffEditor.removedTextBackground": "#fb817f24",
  "diffEditor.insertedLineBackground": "#7ad59c12",
  "diffEditor.removedLineBackground": "#fb817f14",
  "diffEditor.border": R.cizgi,
  "diffEditor.diagonalFill": R.cizgiYumusak,
  "diffEditorGutter.insertedLineBackground": "#7ad59c1a",
  "diffEditorGutter.removedLineBackground": "#fb817f1a",
  "diffEditorOverview.insertedForeground": `${R.tamam}88`,
  "diffEditorOverview.removedForeground": `${R.sil}88`,
  "multiDiffEditor.headerBackground": R.murekkep2,
  "multiDiffEditor.border": R.cizgi,

  // panel, terminal, durum çubuğu, başlık
  "panel.background": R.murekkep,
  "panel.border": R.cizgi,
  "panelTitle.activeForeground": R.kagit,
  "panelTitle.inactiveForeground": R.sonuk2,
  "panelTitle.activeBorder": MERCAN,
  "panelInput.border": R.cizgi,
  "panelSection.border": R.cizgi,
  "panelSectionHeader.background": R.murekkep2,
  "outputView.background": R.murekkep,
  "terminal.background": R.murekkep,
  "terminal.foreground": R.kagit,
  "terminal.border": R.cizgi,
  "terminalCursor.foreground": MERCAN,
  "terminal.selectionBackground": `${MERCAN}40`,
  "terminal.ansiBlack": R.murekkep4,
  "terminal.ansiRed": R.sil,
  "terminal.ansiGreen": R.tamam,
  "terminal.ansiYellow": R.uyari,
  "terminal.ansiBlue": R.tur,
  "terminal.ansiMagenta": "#d7a6e8",
  "terminal.ansiCyan": "#8fd6cf",
  "terminal.ansiWhite": R.kemik,
  "terminal.ansiBrightBlack": R.sonuk2,
  "terminal.ansiBrightRed": MERCAN_ACIK,
  "terminal.ansiBrightGreen": "#a3e6bb",
  "terminal.ansiBrightYellow": "#f6d98e",
  "terminal.ansiBrightBlue": "#b9def2",
  "terminal.ansiBrightMagenta": "#e6c3f1",
  "terminal.ansiBrightCyan": "#b5e8e2",
  "terminal.ansiBrightWhite": R.kagit,
  "terminalCommandDecoration.defaultBackground": R.sonuk2,
  "terminalCommandDecoration.successBackground": R.tamam,
  "terminalCommandDecoration.errorBackground": R.sil,
  "statusBar.background": R.murekkep2,
  "statusBar.foreground": R.sonuk,
  "statusBar.border": R.cizgi,
  "statusBar.focusBorder": MERCAN,
  "statusBar.noFolderBackground": R.murekkep2,
  "statusBar.noFolderForeground": R.sonuk,
  "statusBar.debuggingBackground": MERCAN,
  "statusBar.debuggingForeground": R.murekkep,
  "statusBarItem.hoverBackground": R.murekkep4,
  "statusBarItem.hoverForeground": R.kagit,
  "statusBarItem.activeBackground": R.murekkep5,
  "statusBarItem.remoteBackground": R.murekkep2,
  "statusBarItem.remoteForeground": R.sonuk,
  "statusBarItem.prominentBackground": R.murekkep4,
  "statusBarItem.prominentForeground": R.kagit,
  "statusBarItem.warningBackground": `${MERCAN}2e`,
  "statusBarItem.warningForeground": MERCAN_ACIK,
  "statusBarItem.errorBackground": "#fb817f33",
  "statusBarItem.errorForeground": R.sil,
  "statusBarItem.focusBorder": MERCAN,
  "titleBar.activeBackground": R.murekkep,
  "titleBar.activeForeground": R.kemik,
  "titleBar.inactiveBackground": R.murekkep,
  "titleBar.inactiveForeground": R.sonuk2,
  "titleBar.border": R.cizgi,
  "commandCenter.background": R.murekkep3,
  "commandCenter.foreground": R.sonuk,
  "commandCenter.border": R.cizgi,
  "commandCenter.activeBackground": R.murekkep4,
  "menu.background": R.murekkep2,
  "menu.foreground": R.kagit,
  "menu.border": R.cizgiGuclu,
  "menu.selectionBackground": R.murekkep4,
  "menu.selectionForeground": R.kagit,
  "menu.separatorBackground": R.cizgi,
  "menubar.selectionBackground": R.murekkep4,
  "menubar.selectionForeground": R.kagit,
  "toolbar.hoverBackground": R.murekkep4,
  "toolbar.activeBackground": R.murekkep5,

  // hızlı giriş, bildirimler, ipuçları
  "quickInput.background": R.murekkep2,
  "quickInput.foreground": R.kagit,
  "quickInputTitle.background": R.murekkep3,
  "quickInputList.focusBackground": R.murekkep4,
  "quickInputList.focusForeground": R.kagit,
  "pickerGroup.foreground": MERCAN_ACIK,
  "pickerGroup.border": R.cizgi,
  "notifications.background": R.murekkep2,
  "notifications.foreground": R.kagit,
  "notifications.border": R.cizgi,
  "notificationCenter.border": R.cizgiGuclu,
  "notificationCenterHeader.background": R.murekkep3,
  "notificationToast.border": R.cizgiGuclu,
  "notificationsErrorIcon.foreground": R.sil,
  "notificationsWarningIcon.foreground": R.uyari,
  "notificationsInfoIcon.foreground": R.tur,
  "notificationLink.foreground": MERCAN_ACIK,
  "banner.background": R.murekkep3,
  "banner.foreground": R.kagit,
  "banner.iconForeground": MERCAN,
  "peekView.border": MERCAN,
  "peekViewEditor.background": R.murekkep2,
  "peekViewEditor.matchHighlightBackground": `${R.sayi}40`,
  "peekViewResult.background": R.murekkep2,
  "peekViewResult.selectionBackground": R.murekkep4,
  "peekViewResult.matchHighlightBackground": `${R.sayi}40`,
  "peekViewTitle.background": R.murekkep3,
  "peekViewTitleLabel.foreground": R.kagit,
  "peekViewTitleDescription.foreground": R.sonuk,
  "editorMarkerNavigation.background": R.murekkep2,
  "editorMarkerNavigationError.background": R.sil,
  "editorMarkerNavigationWarning.background": R.uyari,
  "problemsErrorIcon.foreground": R.sil,
  "problemsWarningIcon.foreground": R.uyari,
  "problemsInfoIcon.foreground": R.tur,
  "settings.headerForeground": R.kagit,
  "settings.modifiedItemIndicator": MERCAN,
  "settings.focusedRowBackground": R.murekkep3,
  "settings.rowHoverBackground": R.murekkep2,
  "settings.focusedRowBorder": R.cizgi,
  "settings.sashBorder": R.cizgi,
  "welcomePage.background": R.murekkep,

  // kaynak denetimi ve dosya süsleri
  "gitDecoration.modifiedResourceForeground": R.uyari,
  "gitDecoration.addedResourceForeground": R.tamam,
  "gitDecoration.untrackedResourceForeground": R.tamam,
  "gitDecoration.deletedResourceForeground": R.sil,
  "gitDecoration.renamedResourceForeground": R.tur,
  "gitDecoration.conflictingResourceForeground": MERCAN_ACIK,
  "gitDecoration.ignoredResourceForeground": R.sonuk2,
  "scm.historyItemAdditionsForeground": R.tamam,
  "scm.historyItemDeletionsForeground": R.sil,
  "charts.red": R.sil,
  "charts.yellow": R.uyari,
  "charts.green": R.tamam,
  "charts.blue": R.tur,
  "charts.orange": R.etiket,
  "charts.purple": "#d7a6e8",
  "charts.foreground": R.kagit,
  "charts.lines": R.cizgiGuclu,
};

const sozdizimi = [
  { scope: ["comment", "punctuation.definition.comment"], settings: { foreground: R.sonuk2, fontStyle: "italic" } },
  {
    scope: ["keyword", "keyword.control", "storage", "storage.type", "storage.modifier", "keyword.operator.new", "keyword.operator.expression", "keyword.operator.logical.python"],
    settings: { foreground: MERCAN_ACIK },
  },
  { scope: ["keyword.operator", "punctuation.separator.key-value"], settings: { foreground: "#c9c4bb" } },
  { scope: ["punctuation", "meta.brace", "punctuation.definition.tag"], settings: { foreground: R.sonuk } },
  { scope: ["string", "string.quoted", "string.template", "markup.inline.raw"], settings: { foreground: R.dize } },
  { scope: ["string.regexp", "constant.character.escape", "constant.other.placeholder"], settings: { foreground: R.etiket } },
  { scope: ["constant.numeric", "constant.language", "constant.other.color", "support.constant"], settings: { foreground: R.sayi } },
  {
    scope: ["entity.name.type", "entity.name.class", "entity.other.inherited-class", "support.type", "support.class", "storage.type.primitive", "entity.name.namespace"],
    settings: { foreground: R.tur },
  },
  { scope: ["entity.name.function", "support.function", "meta.function-call entity.name.function", "variable.function"], settings: { foreground: R.etiket } },
  { scope: ["variable", "variable.other", "meta.definition.variable", "support.variable"], settings: { foreground: R.kagit } },
  { scope: ["variable.parameter", "meta.parameter"], settings: { foreground: R.kemik, fontStyle: "italic" } },
  { scope: ["variable.language", "variable.language.this", "variable.language.self"], settings: { foreground: MERCAN_ACIK, fontStyle: "italic" } },
  { scope: ["variable.other.property", "variable.other.object.property", "support.type.property-name", "meta.object-literal.key"], settings: { foreground: R.kemik } },
  { scope: ["entity.name.tag", "meta.tag.sgml"], settings: { foreground: R.etiket } },
  { scope: ["entity.other.attribute-name"], settings: { foreground: R.tur } },
  { scope: ["support.type.property-name.json", "support.type.property-name.css", "support.type.property-name.yaml", "entity.name.tag.yaml"], settings: { foreground: R.tur } },
  { scope: ["markup.heading", "entity.name.section"], settings: { foreground: MERCAN_ACIK, fontStyle: "bold" } },
  { scope: ["markup.bold"], settings: { fontStyle: "bold" } },
  { scope: ["markup.italic"], settings: { fontStyle: "italic" } },
  { scope: ["markup.underline.link", "string.other.link"], settings: { foreground: R.tur } },
  { scope: ["markup.quote"], settings: { foreground: R.sonuk, fontStyle: "italic" } },
  { scope: ["markup.list", "punctuation.definition.list"], settings: { foreground: MERCAN_ACIK } },
  { scope: ["markup.inserted", "meta.diff.header.to-file", "punctuation.definition.inserted"], settings: { foreground: R.tamam } },
  { scope: ["markup.deleted", "meta.diff.header.from-file", "punctuation.definition.deleted"], settings: { foreground: R.sil } },
  { scope: ["markup.changed", "punctuation.definition.changed"], settings: { foreground: R.uyari } },
  { scope: ["meta.diff.range", "meta.diff.header"], settings: { foreground: R.tur } },
  { scope: ["invalid", "invalid.illegal"], settings: { foreground: R.sil } },
  { scope: ["entity.name.function.decorator", "meta.decorator", "punctuation.decorator"], settings: { foreground: R.etiket, fontStyle: "italic" } },
];

/** VS Code renk teması dosyası (contributes.themes ile yüklenir) */
export const fyTemasi = {
  $schema: "vscode://schemas/color-theme",
  name: TEMA_ADI,
  type: "dark",
  semanticHighlighting: true,
  colors: renkler,
  tokenColors: sozdizimi,
  semanticTokenColors: {
    "variable.readonly": R.kagit,
    "property.readonly": R.kemik,
    enumMember: R.sayi,
    "type.defaultLibrary": R.tur,
    "function.defaultLibrary": R.etiket,
  },
};

/** Tema yüklenene kadar kullanılan ilk renkler: açılışta beyaz parlama olmasın */
export const ILK_RENKLER: Record<string, string> = {
  "editor.background": R.murekkep,
  "editor.foreground": R.kagit,
  "sideBar.background": R.murekkep2,
  "activityBar.background": R.murekkep,
  "statusBar.background": R.murekkep2,
  "titleBar.activeBackground": R.murekkep,
  "panel.background": R.murekkep,
  "editorGroupHeader.tabsBackground": R.murekkep2,
};
