// Ayarlar (Türkçe)
export const ayarlar = {
  baslik: "Ayarlar",
  aciklama: "Çekirdek ayarları bütün projeler için geçerlidir",
  alinamadi: "Ayarlar alınamadı.",
  kaydedildi: "Ayarlar kaydedildi.",
  degisiklikYok: "Değişiklik yok",
  /** Dil bölümünün başlığı s.genel.dil; seçenekler kendi dillerinde yazılır (Türkçe, English) */
  dil: {
    aciklama: "Arayüz ve ajanlar bu dili kullanır. Çalışan ajanlar bir sonraki oturumlarında yeni dile geçer.",
  },
  claude: {
    baslik: "Claude Code",
  },
  github: {
    baslik: "GitHub",
  },
  projeKoku: {
    baslik: "Proje kökü",
    aciklama: "Yeni projeler ve GitHub'dan indirilen depolar bu klasörde açılır.",
    varsayilanEtiket: "varsayılan",
    degistir: "Değiştir",
    varsayilan: "Varsayılana dön",
    secBaslik: "Proje kökünü seçin",
    kaydedildi: (yol: string) => `Proje kökü ${yol} oldu.`,
  },
  kurulum: {
    baslik: "İlk kurulum",
    aciklama: "Dil, Claude Code, GitHub, ilk proje ve hazırlık adımlarını yeniden gösterir. Ayarlarınız ve projeleriniz olduğu gibi kalır.",
    ac: "İlk kurulum sihirbazını yeniden aç",
  },
  giris: {
    baslik: "Abonelik ve sınırlar",
    /** " · giriş: claude.ai" */
    kaynak: "giriş",
    ulasilamadi: (hata: string) => `Claude Code'a ulaşılamadı: ${hata}`,
    okunmadi: "Claude Code girişi henüz okunmadı.",
    sifirlanma: (zaman: string) => `sıfırlanma ${zaman}`,
    yenidenOku: "Girişi yeniden oku",
    abonelik:
      "ArnOrg yalnız Claude aboneliğiyle çalışır: ajanlar bu makinedeki Claude Code girişinizle (Pro, Max ya da Team) çalışır. Planın 5 saatlik ve haftalık pencereleri sayılır; ortamda API anahtarı olsa da ajanlara verilmez.",
    besSaat: "5 saatlik pencere üst sınırı (%)",
    besSaatIpucu: "Ajanlar bu yüzdede durur, kalanı sizin kullanımınıza kalır. 0 sınırsız.",
    hafta: "Haftalık pencere üst sınırı (%)",
    haftaIpucu: "Pencere sıfırlanınca ajanlar kaldıkları yerden sürer.",
  },
  /** Aynı anda çalışan ajan tavanı, görev token tavanı, açılışta yarım kalan işe dönüş */
  calismaDuzeni: {
    baslik: "Çalışma düzeni",
    esZamanli: "Aynı anda çalışan ajan (üst sınır)",
    esZamanliIpucu:
      "Bütün projelerde aynı anda iş yapan en çok ajan. Tam otonom projede ekip temposunu CEO bu sınırın altında kendisi belirler; kurul kipinde bu sınır geçerlidir. Sınır doluyken gelen iş sıraya girer, yer açılınca sırayla başlar. 0 sınırsız.",
    esZamanliHata: "0 ile 50 arasında bir tam sayı olmalı.",
    tavan: "Görev token tavanı (milyon)",
    tavanIpucu: "Bir görev bu kadar token işleyince ajanı durur ve sürmesi için onayınız istenir; onaylarsanız tavan bir kat artar. 0 kapalı.",
    tavanHata: "0 ile 1000 arasında olmalı.",
    surdur: "Açılışta yarım kalan işe dön",
    surdurIpucu: "ArnOrg yeniden açılınca, kapanırken çalışan ajanlar aynı konuşmayla kaldıkları yerden sürer. Mesaiyi durdur ile durdurulanlar uyanmaz.",
  },
  cekirdek: {
    baslik: "Çekirdek",
    claudeYolu: "Claude Code yolu",
    claudeYoluOrnek: "Boş: önce PATH, sonra SDK ile gelen ikili",
    ghYolu: "GitHub CLI (gh) yolu",
    ghYoluOrnek: "Boş: önce PATH, sonra ArnOrg'un indirdiği kopya",
    izinModu: "Varsayılan izin modu",
    izinModuIpucu: "Her çağrı modu ne olursa olsun PreToolUse kapısından geçer.",
    sure: "Karar süresi (saniye)",
    sureHata: "En az 10 saniye.",
    sureIpucu: "Süre dolunca bekleyen araç çağrısı reddedilir.",
    saklama: "Denetim kaydı saklama (gün)",
    saklamaHata: "0 ile 3650 arasında tam gün olmalı.",
    saklamaIpucu: "Daha eski kayıtlar veri dizinindeki arsiv klasörüne aylık JSONL dosyaları olarak taşınır. 0 süresiz tutar.",
    tikanma: "Tıkanma eşiği (dakika)",
    tikanmaHata: "0 ile 1440 arasında olmalı.",
    tikanmaIpucu: "Bu süre ilerlemeyen görevin sorumlusu hatırlatılır, sonra yöneticiye ve kurula iletilir. 0 kapatır.",
    editor: "Dış editör",
    editorBaska: "Başka bir komut…",
    editorKomutu: "Editör komutu",
  },
  kodZekasi: {
    baslik: "Kod zekâsı",
    model: "Anlamsal arama modeli",
    modeller: { kaliteli: "Kaliteli", hizli: "Hızlı", kapali: "Kapalı" },
    kapaliIpucu: "Kod yalnız anahtar sözcük ve sembol adıyla aranır; model indirilmez.",
    modelIpucu: "Model ilk kullanımda indirilir ve bu makinede çalışır; kod dışarı gönderilmez.",
    indirildi: (mb: number) => `İndirildi (${mb} MB).`,
    indirilecek: (mb: number) => `İlk kullanımda ~${mb} MB indirilir.`,
    yerel: "Model bu makinede çalışır; kod dışarı gönderilmez.",
    otomatik: "Projeleri otomatik dizinle",
    otomatikIpucu:
      "Açıkken ArnOrg açılınca ve proje eklenince ana repo arka planda dizinlenir; değişen dosyalar kendiliğinden güncellenir. Kapalıyken ilk arama dizinlemeyi başlatır.",
  },
  sistem: {
    baslik: "Sistem",
    bulundu: "Bulundu",
    bulunamadi: "Bulunamadı",
    yol: "Yol",
    veriDizini: "Veri dizini",
    uyari: "Ajanlar başlatılamaz. Claude Code'u kurun ya da yolunu yukarıda belirtin.",
  },
  tarayici: {
    baslik: "Bu tarayıcı",
    sirketAdi: "Üst çubukta görünen şirket adı",
    uygula: "Uygula",
    yerel: "Yalnız bu tarayıcıda saklanır.",
    sirketGuncellendi: "Şirket adı güncellendi.",
    baglanti: "Bağlantı",
    anahtariUnut: "Anahtarı unut",
    baglantiyiKes: "Bu sekmede bağlantıyı kes",
    anahtarIpucu: "Erişim anahtarı sessionStorage'da durur; unutulunca yeniden yapıştırmanız gerekir.",
  },
  hakkinda: {
    baslik: "Hakkında",
  },
};
