// 0.0.10 · Kullanım seviyesi (Zeki, Normal, Tasarruflu) ve proje token bütçesi: proje açılışı, Proje ayarları, üst
// çubuktaki bütçe göstergesi ve paneli, Karargâh'taki harcama, Pano'da görev tokenı, çalışanın modelinde seviye
export const butce = {
  seviye: {
    baslik: "Kullanım seviyesi",
    adlar: { zeki: "Zeki", normal: "Normal", tasarruflu: "Tasarruflu" },
    aciklamalar: {
      zeki: "En güçlü modeller ve derin düşünme; zor işler için. Aboneliği en hızlı bu tüketir.",
      normal: "Güç ve harcama dengede; çoğu proje için.",
      tasarruflu: "Hafif modeller ve kısa düşünme; basit işler ve dar bütçe için.",
    },
    kademeler: { yonetim: "CEO, CTO, kod inceleme", gelistirme: "Geliştirme", destek: "Test, doküman, tanıtım" },
    derinlik: { high: "derin düşünme", medium: "orta düşünme", low: "kısa düşünme" },
    tavan: (t: string) => `görev tavanı ${t}`,
    tavanKapali: "görev tavanı kapalı",
    tempo: (n: number) => `aynı anda en çok ${n} çalışan`,
    tempoSinirsiz: "aynı anda çalışan sınırsız",
    degisti: (ad: string) => `Kullanım seviyesi ${ad} oldu.`,
  },
  butce: {
    baslik: "Token bütçesi",
    toplam: "Toplam bütçe",
    gunluk: "Günlük bütçe",
    birim: "milyon token",
    sinirsiz: "Sınırsız",
    milyon: (m: number) => `${m} M`,
    hazirEtiket: (ad: string) => `${ad}: hazır değerler`,
    toplamIpucu: "Projenin bütün kullanımı. Dolunca ekip durur; bütçeyi artırınca kaldığı yerden sürer.",
    gunlukIpucu: "Her gece yarısı yenilenir. Dolunca ekip ertesi güne dek durur.",
    hata: "Sayı yazın (ör. 20 ya da 2,5); boş bırakırsanız sınırsız.",
    harcanan: (toplam: string, bugun: string) => `Şu ana dek ${toplam} token harcandı; bugün ${bugun}.`,
    kaydet: "Bütçeyi kaydet",
    kaydedildi: "Bütçe kaydedildi.",
  },
  kademe: {
    etiket: "Otomatik kademe düşürme",
    ipucu: "Bütçenin ya da haftalık abonelik penceresinin %80'i geçilince seviye bir kademe iner, koşul kalkınca geri çıkar. Bütçenin %80'inde siz ve CEO uyarılırsınız.",
    acildi: "Otomatik kademe düşürme açıldı.",
    kapandi: "Otomatik kademe düşürme kapandı.",
  },
  acilis: {
    baslik: "Kullanım ve bütçe",
    aciklama: "Seviye çalışanların modelini ve düşünme derinliğini belirler; bütçe projenin harcayacağı tokenı sınırlar. İkisini de sonra Proje ayarlarından ya da üst çubuktan değiştirebilirsiniz.",
  },
  ayar: {
    baslik: "Kullanım ve bütçe",
    kademede: (etkin: string, secilen: string, neden: string) => `Şu an ${etkin} seviyede çalışıyor (${neden}); koşul kalkınca ${secilen} seviyesine döner.`,
    nedenler: {
      butce: "bütçenin %80'i harcandı",
      pencere: (ad: string) => `abonelik penceresi: ${ad} %80'i geçti`,
    },
    elleNotu: "Bir çalışana elle seçtiğiniz model korunur; çalışanın modelinde “Seviyeye göre”yi seçerek yeniden seviyeye bağlarsınız.",
  },
  gosterge: {
    butce: "Bütçe",
    bugun: "Bugün",
    toplam: "Toplam",
    birim: "token",
    /** Seviye etiketi; kademe inmişse ok işaretiyle */
    seviyeEtiketi: (ad: string) => `Seviye: ${ad}`,
    baslik: (parcalar: string[]) => `${parcalar.join(" · ")}. Ayrıntı ve bütçe için tıklayın.`,
    kalem: (ad: string, harcanan: string, sinir: string, yuzde: string) => `${ad} ${harcanan} / ${sinir} (${yuzde})`,
    toplamKalem: (toplam: string) => `Toplam ${toplam} token`,
    seviyeKalem: (ad: string) => `seviye ${ad}`,
    doldu: "bütçe doldu, ekip duruyor",
  },
  panel: {
    baslik: "Kullanım ve bütçe",
    kapat: "Paneli kapat",
    seviye: "Seviye",
    gecerli: (etkin: string, neden: string) => `Şu an ${etkin} (${neden})`,
    toplam: "Toplam",
    gunluk: "Bugün",
    butceYok: "Bütçe yok: proje sınırsız harcar.",
    harcandi: (t: string) => `${t} token harcandı`,
    tahmin: (sure: string, an: string) => `Bu hızla yaklaşık ${sure} sonra dolar (${an}).`,
    tahminYok: "Bitiş tahmini için son bir saatte yeterli kullanım yok.",
    sure: {
      gun: (n: number) => `${n} gün`,
      saat: (n: number) => `${n} sa`,
      dakika: (n: number) => `${n} dk`,
    },
    doldu: { toplam: "Proje bütçesi doldu; ekip duruyor. Bütçeyi artırınca kaldığı yerden sürer.", gunluk: "Bugünkü bütçe doldu; ekip gece yarısına dek duruyor. Bütçeyi artırırsanız hemen sürer." },
    uyari: (yuzde: string) => `Bütçenin ${yuzde}'i harcandı.`,
    artir: "Bütçeyi artır",
    butceKoy: "Bütçe koy",
    adim: (m: string) => `${m} yap`,
    vazgec: "Vazgeç",
    kaydet: "Kaydet",
    artirildi: "Bütçe güncellendi.",
    pahali: "En pahalı görevler",
    tumu: "Karargâh'ta harcama",
  },
  harcama: {
    baslik: "Harcama",
    gorevler: "En pahalı görevler",
    gorevlerBos: "Henüz görevlere token yazılmadı; çalışanlar bir görev üstünde çalışırken işlenen token o göreve sayılır.",
    calisanlar: "Çalışan başına (bugüne dek)",
    calisanlarBos: "Henüz token harcanmadı.",
    atanmadi: "atanmamış",
    tavan: (tavan: string) => `tavan ${tavan}`,
    gorevAc: (kod: string) => `${kod} görevini Pano'da aç`,
  },
  gorev: {
    tokenBaslik: (tam: string, tavan: string | null) => `Bu görevde işlenen token: ${tam}${tavan ? ` · görev tavanı ${tavan}` : ""}`,
    harcanan: "Harcanan token",
    tavanli: (t: string, tavan: string) => `${t} / ${tavan} (görev tavanı)`,
  },
  model: {
    seviyeyeGore: (model: string) => `Seviyeye göre · ${model}`,
    seviyeyeGoreKisa: "seviyeye göre",
    sabit: "elle seçildi",
    baglandi: (ad: string, model: string) => `${ad} artık seviyeye göre çalışıyor (${model}).`,
  },
  bildirim: {
    artir: "Bütçeyi artır",
  },
};
