// Denetim ve politika (Türkçe)
import type { KuralHedefi } from "@arnorg/ortak";

export const denetim = {
  baslik: "Denetim",
  altBaslik: "Her araç çağrısı ArnOrg'un kapısından geçer · politika .arnorg/proje.yaml",
  bekleyenler: "Karar bekleyen çağrılar",
  bekliyor: (n: number) => `${n} bekliyor`,
  bekleyenYokKisa: "yok",
  bekleyenYok: 'Şu an kararınızı bekleyen çağrı yok. "Onaya sor" kuralına takılan çağrılar burada belirir; süre dolarsa çağrı reddedilir.',
  sonKararlar: "Son kararlar",
  kapi: "PreToolUse kapısı",
  karaGore: "Karara göre süz",
  ajanaGore: "Ajana göre süz",
  butunAjanlar: "Bütün ajanlar",
  araEtiket: "Kayıtlarda ara",
  araYer: "Ara: komut, yol, kural",
  disaAktar: "Dışa aktar",
  disaAktarIpucu: "Süzgece uyan kayıtları JSONL dosyası olarak indir (eskiden yeniye)",
  disaAktarBos: "Süzgece uyan kayıt yok; dosya indirilmedi.",
  eslesenYok: "Eşleşen kayıt yok",
  eslesenYokMetin: "Süzgeçleri gevşetin.",
  henuzYok: "Henüz kayıt yok",
  henuzYokMetin: "Ajanlar çalışmaya başlayınca her araç çağrısı ve verilen karar burada listelenir.",
  sutun: {
    saat: "Saat",
    ajan: "Ajan",
    arac: "Araç",
    girdi: "Girdi",
    karar: "Karar",
    kural: "Kural",
  },
  dahaGoster: (n: number) => `${n} kayıt daha göster`,
  /** Çağrıyı ajanın Agent aracıyla açtığı alt ajan yaptıysa ajan adının yanında */
  altAjan: "alt ajan",
  altAjanIpucu: (kimlik: string) => `Bu çağrıyı ajanın açtığı bir alt ajan yaptı · ${kimlik}`,
  politika: "Politika",
  politikaAlt: "izin · ret · onaya sor",

  /** Karar bekleyen araç çağrısı */
  cagri: {
    ajan: "Ajan",
    bilinmeyenAjan: "Bilinmeyen ajan",
    etiket: (ajan: string) => `${ajan} için karar bekleyen çağrı`,
    karar: (ajan: string, arac: string, izin: boolean) => `${ajan} · ${arac}: ${izin ? "izin verildi" : "reddedildi"}.`,
    doldu: "Süre doldu · reddedilecek",
    kaldi: (sure: string) => `${sure} kaldı`,
    kural: (kural: string) => `Kural: ${kural}`,
    notEtiketi: "Karar notu (isteğe bağlı)",
    notYer: "Not (isteğe bağlı) · örn. Dalını it, PR aç",
    izinVer: "İzin ver",
    reddet: "Reddet",
  },

  /** Politika kuralları düzenleyicisi */
  kural: {
    hedefler: {
      komut: "Kabuk komutu",
      yol: "Dosya yolu",
      url: "Adres (URL)",
      arac: "Araç adı",
    } as Record<KuralHedefi, string>,
    yeniKural: "Yeni kural",
    alinamadi: "Politika alınamadı.",
    kaydedildi: "Politika kaydedildi. Yeni çağrılar bu kurallarla denetlenir.",
    yokBaslik: "Kural yok",
    yokMetin: "Kural yoksa her araç çağrısına izin verilir. Yıkıcı komutlar için en az bir ret kuralı ekleyin.",
    anahtar: (ad: string, etkin: boolean) => `${ad} kuralı ${etkin ? "etkin" : "kapalı"}`,
    desenYok: " · desen yok",
    karari: (ad: string) => `${ad} kararı`,
    ad: "Ad",
    hedef: "Hedef",
    aciklama: "Açıklama",
    desenler: "Desenler (her satıra bir düzenli ifade, büyük/küçük harf duyarsız)",
    araclar: "Araçlar (virgülle; boşsa hedefe uyan tüm araçlar)",
    yukari: "Yukarı al",
    asagi: "Aşağı al",
    sil: "Kuralı sil",
    ekle: "Kural ekle",
    kaydedilmemis: "Kaydedilmemiş değişiklikler",
    kaydet: "Politikayı kaydet",
    kaydedilemedi: "Politika kaydedilemedi",
    ipucu: "Kurallar yukarıdan aşağı denenir; ilk eşleşen kural kararı verir. Politika repo içinde .arnorg/proje.yaml dosyasında durur.",
  },
};
