// Ekip, organizasyon şeması, işe alım, ajan ayrıntısı ve eylemleri (Türkçe)
import { belirtme, ilgi, yonelme } from "../../yardimcilar/bicim";

export const ekip = {
  baslik: "Ekip",
  /** Karar yetkisine göre: tam otonomda CEO işe alır ve karar verir, kurul kipinde teklif eder */
  altBaslik: (otonom: boolean): string => (otonom ? "Organizasyon şeması · CEO işe alır, kararları o verir" : "Organizasyon şeması · CEO işe alım teklif eder, siz onaylarsınız"),
  iseAl: "İşe al",
  alinamadi: "Ekip alınamadı.",
  bosBaslik: "Henüz kimse yok",
  ilkCalisan: "İlk çalışanı işe al",
  bosMetin:
    "Her projede bir CEO otomatik işe alınır. CEO brief'i aldıktan sonra gereken rolleri teklif eder; isterseniz doğrudan da işe alabilirsiniz.",
  durumRenkleri: "Durum renkleri",
  teklifler: "İşe alım teklifleri",
  bekliyor: (n: number) => `${n} bekliyor`,
  ayrintilari: (ad: string) => `${ad} ayrıntıları`,

  /** İşe alım formu */
  iseAlim: {
    rollerAlinamadi: "Roller alınamadı.",
    rollerYukleniyor: "Roller yükleniyor…",
    adGerekli: "Ad gerekli.",
    adVar: "Bu adda bir çalışan zaten var.",
    alindi: (ad: string) => `${ad} işe alındı; ortak projede ekibe katılıyor.`,
    tekliflerOnaylarda: (otonom: boolean): string => (otonom ? "CEO da işe alır; kararları gerekçesiyle Onaylar'da" : "CEO'nun teklifleri Onaylar'a düşer"),
    ad: "Ad",
    adOrnek: "Aras",
    rol: "Rol",
    model: "Model",
    yonetici: "Yönetici",
    karakter: "Karakter",
    talimat: "Ek talimat (isteğe bağlı)",
    talimatOrnek: "Rol talimatına eklenir. Örn. Ödeme entegrasyonundan önce OWASP denetimi yap.",
    alinamadiBaslik: "İşe alınamadı",
  },

  /** Ajan ayrıntı paneli */
  ayrinti: {
    oturumuAc: "Oturumu aç",
    bugun: "Bugün",
    toplam: "Toplam",
    token: (miktar: string) => `${miktar} token`,
    izinModu: "İzin modu",
    yonetici: "Yönetici",
    gorev: "Görev",
    iseAlindi: "İşe alındı",
    mesajGonder: "Mesaj gönder",
    ayarlar: "Ayarlar",
    model: "Model",
    ozelModelSecenegi: "Özel model kimliği…",
    ozelModel: "Özel model kimliği",
    uygula: "Uygula",
    modelDegisti: (ad: string, model: string) => `${ad} artık ${model} ile çalışıyor.`,
    ayarlarKaydedildi: "Ajan ayarları kaydedildi.",
    plandanCikIpucu: "Önceki izin moduna döner",
    planaAlIpucu: "Ajan yalnız plan yazar, dosya değiştirmez",
    plandanCik: "Plan modundan çık",
    planaAl: "Plan moduna al",
    ekTalimat: "Ek talimat",
    ekTalimatOrnek: "Rol talimatına eklenir. Örn. Testleri her zaman vitest ile yaz.",
    degisiklikleriKaydet: "Değişiklikleri kaydet",
    ofisKarakteri: "Ofis karakteri",
    /** Ayrıntı bölümleri: genel bilgiler ve ajanın kendi zekâsı */
    sekmeler: "Ajan ayrıntısı bölümleri",
    sekmeGenel: "Genel",
    sekmeZeka: "Zekâ",
    istenCikar: "İşten çıkar",
    istenCikarEvet: (ad: string) => `Evet, ${belirtme(ad)} çıkar`,
    istenCikarUyari: (ad: string) =>
      `${ad} işten çıkarılırsa oturumu kapanır ve ekipten ayrılır. Kimlik dosyası (.arnorg/ekip/) repoda kalır; kiraladığı dosyalar devralana geçer.`,
    devralanSoru: "İşleri ve bildikleri kime devredilsin?",
    devralanAciklama: (ad: string) => `Açık işleri, kişisel hafızası, defteri ve açık sözleri ${yonelme(ad)} geçer.`,
    yoneticisi: "yöneticisi",
    devralanYok: "Ekipte devralacak başka çalışan yok; açık işleri boşa düşer.",
    istenCikarildi: (ad: string, devralan: string | null) =>
      devralan ? `${ad} işten çıkarıldı; işleri ve bildikleri ${yonelme(devralan)} devredildi.` : `${ad} işten çıkarıldı.`,
    ceoCikarilamaz: "CEO işten çıkarılamaz; ekibi o yönetir.",
  },

  /** Oturum eylemleri ve mesaj formu (Ekip paneli ve oturum ekranı) */
  eylem: {
    baslat: "Başlat",
    devamEttir: "Devam ettir",
    kes: "Kes",
    kesIpucu: "Çalışan turu durdurur; oturum açık kalır",
    durdur: "Durdur",
    durdurIpucu: "Oturumu kapatır; oturum kimliği saklanır",
    turKesildi: (ad: string) => `${ilgi(ad)} turu kesildi.`,
    oturumKapatildi: (ad: string) => `${ilgi(ad)} oturumu kapatıldı.`,
    basladi: (ad: string) => `${ad} başladı.`,
    ilkTalimat: "İlk talimat (isteğe bağlı)",
    ilkTalimatIpucu: "Boş bırakılırsa atanmış görevden üretilir",
    gorev: "Görev",
    secilmedi: "Seçilmedi",
    ajaniBaslat: (ad: string) => `${belirtme(ad)} başlat`,
    mesajEtiketi: (ad: string) => `${yonelme(ad)} mesaj`,
    mesajYer: (ad: string, kapali: boolean) => `${yonelme(ad)} yazın${kapali ? " · oturum kapalıysa açılır" : ""}`,
    mesajIletildi: (ad: string) => `Mesaj ${yonelme(ad)} iletildi.`,
    turKesildiMesajIletildi: (ad: string) => `${ilgi(ad)} turu kesildi; mesaj iletildi.`,
    hemen: "Hemen",
    hemenAciklama: "(turu keser)",
    hemenIpucu: "Çalışan turu keser ve mesajı hemen işletir",
    enterIpucu: "Enter gönderir · Shift+Enter yeni satır",
  },
};
