// Ortak sözcükler ve durum adları (Türkçe)
import { AJAN_DURUM_ADLARI, GOREV_DURUM_ADLARI, HAFIZA_TURU_ADLARI, KARAR_ADLARI, ONAY_TURU_ADLARI } from "@arnorg/ortak";

export const genel = {
  kaydet: "Kaydet",
  kaydedildi: "Kaydedildi.",
  vazgec: "Vazgeç",
  kapat: "Kapat",
  sil: "Sil",
  duzenle: "Düzenle",
  ekle: "Ekle",
  ara: "Ara",
  yenile: "Yenile",
  yenidenDene: "Yeniden dene",
  yukleniyor: "Yükleniyor…",
  tamam: "Tamam",
  evet: "Evet",
  hayir: "Hayır",
  onayla: "Onayla",
  reddet: "Reddet",
  gonder: "Gönder",
  ac: "Aç",
  geri: "Geri",
  ileri: "İleri",
  devam: "Devam",
  bitir: "Bitir",
  atla: "Atla",
  kopyala: "Kopyala",
  kopyalandi: "Kopyalandı",
  tumu: "Tümü",
  yok: "Yok",
  henuzYok: "Henüz yok",
  bilinmiyor: "Bilinmiyor",
  hata: "Hata",
  bilinmeyenHata: "Bilinmeyen hata",
  kurul: "Yönetim kurulu",
  arnorg: "ArnOrg",
  dil: "Dil",
  /** Ajan, görev, karar, onay ve hafıza türü adları */
  ajanDurumu: AJAN_DURUM_ADLARI,
  gorevDurumu: GOREV_DURUM_ADLARI,
  karar: KARAR_ADLARI,
  onayTuru: ONAY_TURU_ADLARI,
  hafizaTuru: HAFIZA_TURU_ADLARI,
  izinModu: {
    default: "Varsayılan",
    acceptEdits: "Düzenlemeleri kabul et",
    bypassPermissions: "Tam yetki (denetim kapısıyla)",
    plan: "Plan modu",
    dontAsk: "Sormadan",
    auto: "Otomatik",
  } as Record<string, string>,
  calisanSayisi: (n: number) => `${n} çalışan`,
  gorevSayisi: (n: number) => `${n} görev`,
  kayitSayisi: (n: number) => `${n} kayıt`,
  /** Sayıdan sonra gelen birim: "48 bin token" (sayı ayrıca biçimlenir) */
  tokenBirimi: (_n: number) => "token",
  oturumuAc: (ajan: string) => `${ajan} oturumunu aç`,
};
