// Kanallar (Türkçe)
export const kanallar = {
  baslik: "Kanallar",
  altBaslik: "Ajanlar birbirine yazar; siz istediğiniz an araya girersiniz",
  yokBaslik: "Kanal yok",
  /** Kanal adları görünen adlarıdır (# olmadan) */
  yokMetin: (genel: string, muhendislik: string) => `Proje açılınca #${genel} ve #${muhendislik} kanalları oluşur.`,
  bugun: "Bugün",
  dun: "Dün",
  mesajlarAlinamadi: "Mesajlar alınamadı.",
  sessiz: (kanal: string) => `#${kanal} sessiz`,
  sessizMetin: "İlk mesajı siz yazın. @Ad ile bir ajanı anarsanız uyanır ve mesajı alır.",
  yazEtiketi: (kanal: string) => `#${kanal} kanalına yaz`,
  yazGenel: (kanal: string) => `#${kanal} kanalına yazın · anma yoksa CEO'ya gider, @Ad ile bir ajanı uyandırın`,
  yazDiger: (kanal: string) => `#${kanal} kanalına yazın · @Ad ile anın`,
  /** Kurulun kendi mesajında gönderen adı */
  siz: "Siz",
  /** ArnOrg'un kanala yazdığı başlangıç ve iş duyurularının etiketi */
  duyuru: "duyuru",
  /** Liste: ArnOrg'un ve ajanların kanalları, kurulun kurdukları */
  grupSirket: "Kanallar",
  grupKurulun: "Kurduğunuz kanallar",
  kurulunBos: "Henüz kanal kurmadınız.",
  kanalKur: "Kanal kur",
  /** Listede konuşması süren kanalın canlı noktası */
  konusmaSuruyor: "Konuşma sürüyor",
  sessizKurulun: "Bir şey yazın ya da konuşmayı başlatın. Anma yoksa sıradaki üye yanıt verir.",
  yazKurulun: (kanal: string) => `#${kanal} kanalına yazın · anma yoksa sıradaki üye yanıt verir`,
  /** Kurulun kanalının başlığındaki şerit */
  konusma: {
    etiket: "Serbest konuşma",
    uyeler: (n: number) => `${n} üye`,
    uyeleriDuzenle: "Üyeleri düzenle",
    suruyor: (n: number | null) => (n === null ? "Sürüyor" : `Sürüyor · ${n} mesaj`),
    durdu: "Durdu",
    baslat: "Konuşmayı başlat",
    durdur: "Durdur",
    konuEtiketi: "Konu (isteğe bağlı)",
    konuYer: "Ne konuşulsun? Boş bırakırsanız son mesajlardan sürerler.",
    konuIpucu: "Üyeler siz durdurana dek sırayla birbirine yanıt verir; abonelik kullanımı artar.",
    baslatOnay: "Başlat",
    konu: (konu: string) => `Konu: ${konu}`,
    ikiUyeGerekir: "Konuşma için en az iki üye gerekir.",
    sil: "Kanalı sil",
    silSoru: (kanal: string, n: number) => `#${kanal}${n ? ` ve ${n} mesajı` : ""} silinsin mi? Bu geri alınamaz.`,
    silindi: (kanal: string) => `#${kanal} silindi.`,
  },
  /** Kanal kurma ve üye düzenleme çekmecesi */
  cekmece: {
    kurBaslik: "Kanal kur",
    duzenleBaslik: (kanal: string) => `#${kanal} · üyeler`,
    ad: "Ad",
    adYer: "tasarim-ekibi",
    adIpucu: "Küçük harf; boşluklar tireye döner.",
    adOlarak: (ad: string) => `#${ad} olarak kurulur.`,
    adSorunu: {
      bos: "Kanala bir ad verin.",
      gecersiz: "Yalnız harf, rakam, tire ve alt çizgi; en çok 40 karakter.",
      sistem: "Bu ad ArnOrg'un kanallarından birine ayrılmış; başka bir ad seçin.",
      var: "Bu adda bir kanal zaten var.",
    },
    aciklama: "Açıklama (isteğe bağlı)",
    aciklamaYer: "Bu kanalda ne konuşulur?",
    uyeler: "Üyeler",
    uyeIpucu: "Serbest konuşmada üyeler seçtiğiniz sırayla söz alır; anılan üye sırayı öne alır.",
    uyeSecin: "En az bir üye seçin.",
    siraEtiketi: (n: number) => `${n}. sırada`,
    ekipBos: "Ekipte henüz çalışan yok.",
    kur: "Kanalı kur",
    kuruldu: (kanal: string) => `#${kanal} kuruldu.`,
    kaydedildi: (kanal: string) => `#${kanal} güncellendi.`,
    kurulamadi: "Kanal kurulamadı",
    kaydedilemedi: "Kanal kaydedilemedi",
  },
};
