// Kod ekranı ve VS Code tezgâhı (Türkçe)
import { belirtme, yonelme } from "../../yardimcilar/bicim";

export const kod = {
  baslik: "Kod",
  yukleniyor: "Kod düzenleyici yükleniyor",
  yukleniyorMetni: "Kod düzenleyici yükleniyor…",
  acilamadi: "Kod düzenleyici açılamadı",
  ekranAcilamadi: "Kod ekranı açılamadı.",
  dilNotu: "Editör dili yeniden açılışta değişir",
  dilNotuAyrinti: "VS Code çalışırken dil değiştiremez; sayfa yeniden yüklenince yeni dilde açılır.",
  yenidenYukle: "Yeniden yükle",
  // Dar ekran
  genisEkranIster: "Kod düzenleyici geniş ekran ister",
  genisEkranAyrinti: "VS Code düzenleyicisi en az 760 piksel genişlikte açılır. Aşağıda çalışma alanının dosyalarını görebilirsiniz.",
  calismaAlani: "Çalışma alanı",
  dosyalarYukleniyor: "Dosyalar yükleniyor",
  /** Çalışma alanının görünen adı: "main · ana repo", "Emre · arnorg/emre" */
  anaRepo: (dal: string) => `${dal} · ana repo`,
  ajanAlani: (ad: string, dal: string) => `${ad} · ${dal}`,
  ajan: "Ajan",

  // Tezgâh
  urunAdi: "ArnOrg Kod",
  temaAdi: "FY Mürekkep",
  dilAdi: "Türkçe",
  cekirdegeUlasilamadi: "Çekirdeğe ulaşılamadı.",
  beklenmeyenYanit: (durum: number) => `Beklenmeyen yanıt (${durum}).`,
  bulunamadi: (yol: string) => `Bulunamadı: ${yol}`,
  gecersizAdres: (adres: string) => `Geçersiz ArnOrg adresi: ${adres}`,
  alanlarArasiTasima: "Çalışma alanları arasında taşıma yapılamaz; dosyayı kopyalayıp yapıştırın.",
  terminalAcilamadi: (hata: string) => `Terminal açılamadı: ${hata}`,

  eklenti: {
    aciklama: "ArnOrg ajanlarıyla birlikte çalışma: tema, arama, ajan rozetleri ve kaynak denetimi",
    rozetRengi: "Ajanın değiştirdiği dosyanın gezgindeki rozet rengi",
    komut: {
      duraklatVeDuzenle: "Duraklat ve düzenle",
      disaridaAc: "Dış Düzenleyicide Aç",
      yenile: "Yenile",
      commit: "Commit",
      hazirla: "Değişiklikleri Aşamaya Al",
      hazirlaHepsi: "Tüm Değişiklikleri Aşamaya Al",
      geriAl: "Aşamadan Çıkar",
      geriAlHepsi: "Tümünü Aşamadan Çıkar",
      at: "Değişiklikleri At",
      dosyayiAc: "Dosyayı Aç",
      farkAc: "Değişiklikleri Aç",
    },
    degisiklik: {
      M: "Değiştirildi",
      A: "Eklendi",
      D: "Silindi",
      R: "Yeniden adlandırıldı",
      C: "Kopyalandı",
      U: "Çakışma",
      "?": "İzlenmiyor",
    },
    duzenliyor: (ad: string) => `${ad} düzenliyor`,
    alanDegisikligi: (ad: string, tur: string) => `${ad} · ${tur.toLocaleLowerCase("tr-TR")}`,
    degistirdi: (ad: string) => `${ad} değiştirdi`,
    durumOgesiAdi: "ArnOrg: dosyayı düzenleyen ajan",
    durumIpucu: (ad: string) => `${ad} bu dosyayı düzenliyor; dosya size salt okunur. Tıklayın: ${belirtme(ad)} duraklatıp düzenlemeyi alın.`,
    duzenleyenYok: "Bu dosyayı şu an düzenleyen bir ajan yok.",
    duraklatildi: (ad: string) =>
      `${belirtme(ad)} duraklattınız; düzenleme sizde. Kaydettiğinizde dosya 30 saniye ajanlara kilitlenir ve ajana "yeniden oku" notu gider.`,
    duraklatilamadi: (hata: string) => `Ajan duraklatılamadı: ${hata}`,
    disaridaAcilamadi: (hata: string) => `Dış düzenleyici açılamadı: ${hata}`,
    commitIpucu: "Commit mesajı (Ctrl+Enter ile commit)",
    grupCakisan: "Birleştirme Değişiklikleri",
    grupHazirlanan: "Hazırlanan Değişiklikler",
    grupDegisen: "Değişiklikler",
    grupTemel: "Temel dala göre değişiklikler",
    grupTemelDal: (dal: string) => `${yonelme(dal)} göre değişiklikler`,
    dalIpucu: (dal: string) => `${dal} dalı · yenile`,
    islemBasarisiz: (islem: string, hata: string) => `${islem} başarısız: ${hata}`,
    islem: { hazirla: "Aşamaya alma", geriAl: "Aşamadan çıkarma", at: "Değişiklikleri atma" },
    atilsinMi: (dosya: string) => `${dosya} dosyasındaki değişiklikler atılsın mı? Bu geri alınamaz; izlenmeyen dosya silinir.`,
    atilsinMiCok: (n: number) => `${n} dosyadaki değişiklikler atılsın mı? Bu geri alınamaz; izlenmeyen dosyalar silinir.`,
    commitMesajiYazin: "Commit mesajı yazın.",
    commitYok: "Commit'lenecek değişiklik yok.",
    hepsiCommitlensinMi: "Aşamaya alınmış değişiklik yok. Tüm değişiklikler aşamaya alınıp commit edilsin mi?",
    hepsiniCommitEt: "Evet, hepsini commit et",
    commitAtildi: (sha: string) => `Commit atıldı: ${sha}`,
    commitBasarisiz: (hata: string) => `Commit başarısız: ${hata}`,
    farkTemel: (dosya: string, temel: string, ajan: string) => `${dosya} (${temel} ↔ ${ajan})`,
    farkHazirlanan: (dosya: string) => `${dosya} (HEAD ↔ İndeks)`,
    farkCalisma: (dosya: string) => `${dosya} (İndeks ↔ Çalışma Ağacı)`,
    ajan: "ajan",
  },
};
