// İlk kurulum sihirbazı, Claude Code ve GitHub kurulumu, klasör seçici, proje açma (Türkçe)
import { ilgi } from "../../yardimcilar/bicim";

export const kurulum = {
  sihirbaz: {
    baslik: "İlk kurulum",
    adimlarEtiket: "Kurulum adımları",
    adimlar: { dil: "Dil", claude: "Claude Code", github: "GitHub", proje: "İlk proje", hazirlik: "Hazırlık" },
    hazir: "hazır",
    hazirligiAtla: "Hazırlığı atla",
    atlandi: "Hazırlık atlandı. Ayarlar'dan istediğiniz zaman yeniden açabilirsiniz.",
    bitti: "Hazırlık tamam. Ayarlar'dan istediğiniz zaman yeniden açabilirsiniz.",
    geri: "Geri",
    sonra: "Sonra",
    devam: "Devam",
  },
  dil: {
    baslik: "Merhaba. Önce dili seçelim.",
    aciklama:
      "Ben ArnOrg. Claude Code ajanlarından kurulan şirketinizi birkaç adımda birlikte hazırlayacağız: Claude girişi, GitHub, ilk proje ve CEO'nuzla tanışma. İstediğiniz adımı geçebilir, sonra Ayarlar'dan dönebilirsiniz.",
    secimEtiket: "Arayüz dili",
    /** Seçeneğin altında, her zaman kendi dilinde gösterilir */
    selam: "Kurulumu Türkçe yapalım.",
    ipucu: "Ajanlar da bu dilde konuşur; Ayarlar'dan değiştirebilirsiniz.",
  },
  /** Kurulum listesindeki satırların ekran okuyucu durumu */
  liste: { tamam: "hazır", eksik: "eksik", hata: "sorun var", bilgi: "isteğe bağlı" },
  claude: {
    baslik: "Claude hesabınızı bağlayalım.",
    baslikHazir: "Claude Code hazır.",
    aciklama:
      "Ajanlarınız bu bilgisayardaki Claude Code girişinizle çalışır. ArnOrg yalnız Claude aboneliğiyle (Pro, Max ya da Team) çalışır; API anahtarı kullanılmaz.",
    aciklamaHazir: (eposta: string | null) =>
      `${eposta ? `${eposta} hesabıyla` : "Claude aboneliğinizle"} giriş yapılmış. Bu adımı geçebiliriz.`,
    yukleniyor: "Claude Code durumu okunuyor…",
    alinamadi: "Kurulum durumu alınamadı",
    kopya: "Claude Code",
    kaynak: { paket: "ArnOrg'la gelen kopya", sistem: "Sistemdeki claude komutu", ayar: "Ayarlardaki yol" },
    kopyaYok: "Bulunamadı",
    surum: (s: string) => `sürüm ${s}`,
    kopyaYokUyari: "Claude Code bulunamadı. Terminal için kurabilir ya da Ayarlar'da yolunu belirtebilirsiniz.",
    giris: "Giriş",
    girisYapildi: "Giriş yapıldı",
    girisYok: "Giriş yapılmadı",
    girisYap: "Claude hesabınızla giriş yapın",
    girisIpucu: "Tarayıcıda Claude'un giriş sayfası açılır. Girişten sonra sayfa bir kod gösterirse buraya yapıştırırsınız.",
    abonelik: "Abonelik",
    abonelikVar: "Claude aboneliği",
    abonelikYok: "API anahtarı ya da Console girişi",
    abonelikBekliyor: "Girişten sonra denetlenir",
    apiUyari:
      "Bu giriş API anahtarıyla ya da Console hesabıyla yapılmış. ArnOrg yalnız Claude aboneliğiyle çalışır; Pro, Max ya da Team hesabınızla yeniden giriş yapın.",
    yenidenGiris: "Abonelikle yeniden giriş yapın",
    terminal: "Terminal komutu",
    terminalVar: "claude komutu kurulu",
    terminalYok: "Kurulu değil · isteğe bağlı",
    terminalAciklama:
      "Ajanlar ArnOrg'un kendi kopyasıyla çalışır. Bu kurulum yalnız terminalde claude komutunu da kullanmak isterseniz gerekir.",
    terminalKur: "Terminal için de kur",
    girisTamam: "Claude girişi tamam.",
    kurulumTamam: "claude komutu kuruldu.",
    tazele: "Durumu yenile",
  },
  github: {
    baslik: "GitHub'ı bağlayalım mı?",
    baslikHazir: "GitHub bağlı.",
    aciklama:
      "İsteğe bağlı. Bağlarsanız depolarınızdan seçip bilgisayara indirebilir, yeni projeleri GitHub'da da açabilir, onaylı işleri uzak depoya gönderebilirsiniz. gh ve git ayarlarını ArnOrg yapar.",
    aciklamaHazir: (kullanici: string) => `${kullanici} hesabıyla bağlısınız; git kimliğiniz de hazır. Bu adımı geçebiliriz.`,
    yukleniyor: "GitHub ve git durumu okunuyor…",
    git: "git",
    gitVar: (surum: string | null) => (surum ? `git ${surum}` : "Kurulu"),
    gitYok: "Bulunamadı",
    gitLinux: "git'i paket yöneticinizle kurun, sonra durumu yenileyin:",
    gitKur: "git'i kur",
    gitKurWindows: "winget ile Git for Windows kurulur.",
    gitKurMac: "macOS'un geliştirici araçları penceresi açılır; kurulum bitince durumu yenileyin.",
    gitOnce: "Önce git'i kurun.",
    gh: "GitHub CLI",
    ghVar: (surum: string | null, kaynak: string) => `${surum ? `gh ${surum}` : "gh"} · ${kaynak}`,
    ghKaynak: { sistem: "sistemdeki", arnorg: "ArnOrg'un kopyası", ayar: "ayardaki yol" },
    ghYok: "Kurulu değil",
    ghKur: "GitHub CLI'ı kur",
    ghKurIpucu: "ArnOrg gh'yi GitHub'dan indirip kendi klasörüne kurar; yönetici izni gerekmez.",
    ghKuruldu: "GitHub CLI kuruldu.",
    giris: "GitHub girişi",
    girisVar: (kullanici: string) => `${kullanici} olarak bağlı`,
    girisYok: "Giriş yapılmadı",
    girisOnce: "Önce GitHub CLI'ı kurun.",
    girisYap: "GitHub'a giriş yap",
    girisIpucu:
      "Tarayıcıda GitHub açılır; tek kullanımlık kodu girip onaylarsınız. git'in GitHub kimliğini gh'den alması da ayarlanır.",
    girisTamam: (kullanici: string | null) => (kullanici ? `GitHub'a ${kullanici} olarak bağlandınız.` : "GitHub'a bağlandınız."),
    yardimciYok: "git, GitHub kimliğini henüz gh'den almıyor.",
    yardimciAyarla: "git'i gh ile ayarla",
    yardimciTamam: "git, GitHub kimliğini artık gh'den alıyor.",
    kimlik: "git kimliği",
    kimlikVar: (ad: string, eposta: string) => `${ad} · ${eposta}`,
    kimlikYok: "Ad ve e-posta boş",
    kimlikIpucu: "Ajanların commit'leri bu ad ve e-postayla atılır.",
    kimlikGithubdan: "GitHub hesabınızdan dolduruldu; dilerseniz değiştirin.",
    ad: "Ad",
    adOrnek: "Ada Yılmaz",
    eposta: "E-posta",
    epostaOrnek: "ada@ornek.com",
    adGerekli: "Ad gerekli.",
    epostaGecersiz: "Geçerli bir e-posta adresi yazın.",
    kimlikKaydet: "Kimliği kaydet",
    kimlikDegistir: "Değiştir",
    kimlikKaydedildi: "git kimliği kaydedildi.",
    tazele: "Durumu yenile",
  },
  islem: {
    adlar: {
      claude_giris: "Claude girişi",
      claude_kur: "Claude Code kurulumu",
      gh_kur: "GitHub CLI kurulumu",
      gh_giris: "GitHub girişi",
      git_kur: "git kurulumu",
      klonla: "Klonlama",
      github_olustur: "GitHub deposu",
    },
    durumlar: { calisiyor: "Sürüyor", tamam: "Tamamlandı", hata: "Olmadı", iptal: "İptal edildi" },
    gecen: (sure: string) => `${sure} geçti`,
    iptal: "İptal et",
    gizle: "Gizle",
    yenidenDene: "Yeniden dene",
    cikti: "Ayrıntılı çıktı",
    ciktiYok: "Henüz çıktı yok.",
    adresAcildi: "Tarayıcıda giriş sayfası açıldı.",
    adresAc: "Açılmadıysa buradan açın",
    kodYapistir: "Sayfada gösterilen kodu yapıştırın",
    kodOrnek: "Kodu buraya yapıştırın",
    kodGerekli: "Kodu yapıştırın.",
    kodGonder: "Gönder",
    kodDogrulaniyor: "Kod doğrulanıyor…",
    girisBekleniyor: "Tarayıcıda girişi tamamlamanız bekleniyor…",
    cihazKodu: "Tek kullanımlık kod",
    cihazKoduIpucu: "Bu kodu GitHub'daki sayfaya girin.",
    cihazSayfasi: "github.com/login/device sayfasını aç",
    onayBekleniyor: "GitHub'da onaylamanız bekleniyor…",
    ilerleme: "İlerleme",
    asamalar: { indirme: "İndiriliyor", alma: "Nesneler alınıyor", cozme: "Değişiklikler çözümleniyor" },
  },
  proje: {
    baslik: "İlk projeyi açalım.",
    baslikHazir: (ad: string) => `${ad} açık.`,
    aciklama:
      "Yeni bir proje başlatın, GitHub'daki bir depoyu indirin ya da bilgisayarınızdaki bir klasörü bağlayın. Konumu ArnOrg önerir; yol yazmanız gerekmez.",
    varOlan: (n: number) => `Zaten ${n} projeniz var. Yenisini açabilir ya da bu adımı geçebilirsiniz.`,
    kok: (yol: string) => `Yeni projeler ${yol} altında açılır.`,
  },
  hazirlik: {
    baslik: "CEO'nuz sizi bekliyor.",
    aciklama:
      "CEO #yonetim kanalında sizinle projeyi konuşur. Her seferinde tek konu sorar; söyledikleriniz kurul kararı olarak hafızaya yazılır, ana yasa ve işe alımlar onayınıza gelir.",
    konularBaslik: "Konuşulacaklar",
    konular: ["Amaç ve ilk sürümde olması gerekenler", "Teknoloji ve kalite tercihleriniz", "Ana yasa: ekibin uyacağı kurallar", "İlk işe alımlar"],
    proje: "Proje",
    dal: "Çalışma dalı",
    uzak: "Uzak depo",
    uzakYok: "Yok",
    baslat: "Hazırlık görüşmesini başlat",
    sonra: "Şimdilik geç",
    sonraIpucu: "Görüşmeyi daha sonra Karargâh'tan başlatabilirsiniz.",
    basladi: "Hazırlık başladı. CEO #yonetim kanalında ilk sorusunu soruyor.",
    suruyor: (ad: string) => `${ilgi(ad)} hazırlık görüşmesi sürüyor.`,
    tamam: (ad: string) => `${ilgi(ad)} hazırlığı tamamlanmış.`,
    karargah: "Karargâh'a git",
    projeYok: "Hazırlık görüşmesi için önce bir proje açın.",
    projeyeDon: "Proje adımına dön",
    bitir: "Hazırlığı bitir",
  },
  ac: {
    sekmeEtiket: "Projeyi nereden açalım?",
    sekmeler: { yeni: "Yeni proje", github: "GitHub'dan aç", klasor: "Bilgisayarımdaki klasör" },
    ad: "Proje adı",
    adOrnek: "Sipariş Paneli",
    adGerekli: "Proje adı gerekli.",
    aciklama: "Açıklama (isteğe bağlı)",
    aciklamaOrnek: "Küçük işletmeler için sipariş ve kargo takibi",
    dal: "Çalışma dalı",
    dalIpucu: "Ajanlar bu daldan dallanır; onaylı birleştirmeler bu dala girer.",
    dalGecersiz: "Geçerli bir dal adı yazın (boşluk, .. ve ~^:?*[ olmadan).",
    github: "GitHub'da da depo aç",
    githubIpucu: "Depo açılır ve proje iskeleti ilk commit'le gönderilir.",
    githubYok: "GitHub bağlı değil.",
    githubBagla: "GitHub'ı bağla",
    gorunurluk: "Görünürlük",
    ozel: "Özel",
    acik: "Açık",
    sahip: "Sahip",
    sahipSiz: (kullanici: string) => `${kullanici} (siz)`,
    olustur: "Projeyi oluştur",
    acilamadi: "Proje açılamadı",
    acildi: (ad: string) => `${ad} açıldı. CEO işe alındı.`,
  },
  konum: {
    etiket: "Konum",
    ipucu: "Proje klasörü burada açılır.",
    degistir: "Değiştir",
    varsayilan: "Varsayılana dön",
    elle: "Yolu elle yaz",
    elleKapat: "Otomatik konuma dön",
    elleEtiket: "Klasörün tam yolu",
    elleOrnek: "/home/siz/projeler/siparis-paneli",
    mutlak: "Mutlak bir yol yazın (ör. /home/siz/projeler/siparis-paneli).",
    secBaslik: "Projenin açılacağı klasörü seçin",
    adYeri: "proje-adi",
  },
  depo: {
    ara: "Depolarda ara",
    araOrnek: "Depo adı ya da açıklama",
    liste: "Depolarınız",
    yukleniyor: "Depolar yükleniyor…",
    alinamadi: "Depolar alınamadı",
    bos: "Hesabınızda henüz depo yok.",
    eslesmeYok: (q: string) => `“${q}” ile eşleşen depo yok.`,
    ozel: "Özel",
    acik: "Açık",
    bosDepo: "boş depo",
    guncellendi: (zaman: string) => `güncellendi ${zaman}`,
    secin: "Listeden bir depo seçin.",
    dallarAlinamadi: "Dallar alınamadı",
    projeAdi: "Proje adı",
    klonla: "Klonla ve aç",
    girisGerekli: "Depolarınızı listelemek için önce GitHub'ı bağlayalım.",
    acildi: (ad: string) => `${ad} indirildi ve açıldı.`,
  },
  dal: {
    varsayilan: "varsayılan",
    korumali: "korumalı",
    yeni: "Yeni dal…",
    yeniAd: "Yeni dalın adı",
    yeniOrnek: "gelistirme",
    listeyeDon: "Listeden seç",
    bosDepo: "Depo boş; çalışma dalı bu adla açılır.",
    yukleniyor: "Dallar yükleniyor…",
    yerel: "Bu bilgisayarda",
    uzak: "Uzak depoda",
  },
  klasor: {
    aciklama: "Bilgisayarınızdaki bir git deposunu bağlayın. Dosyalarınıza dokunulmaz; yalnız .arnorg/ klasörü eklenir.",
    sec: "Klasör seç",
    baska: "Başka klasör",
    secBaslik: "Bağlanacak klasörü seçin",
    secilen: "Seçilen klasör",
    denetleniyor: "Klasör denetleniyor…",
    denetlenemedi: "Klasör denetlenemedi",
    repo: "git deposu",
    repoDegil: "git deposu değil",
    repoDegilAciklama:
      "Bu klasör henüz bir git deposu değil. ArnOrg burada yeni bir repo başlatabilir: git init yapılır ve klasördeki dosyalar ilk commit'e girer.",
    dalNotu: "Çalışma dalı reponun şu anki dalı olur; Proje ayarları'ndan değiştirebilirsiniz.",
    bagla: "Repoyu bağla",
    baslat: "Burada repo başlat",
  },
  gezgin: {
    baslik: "Klasör seçin",
    kisayollar: "Kısayollar",
    konum: "Konum",
    ust: "Üst klasör",
    yukleniyor: "Klasörler yükleniyor…",
    alinamadi: "Klasör okunamadı",
    evDon: "Ev klasörüne dön",
    bos: "Bu klasörde alt klasör yok.",
    repo: "git",
    repoBaslik: "Bu klasör bir git deposu",
    klasorler: "Alt klasörler",
    yeniKlasor: "Yeni klasör",
    yeniKlasorAd: "Yeni klasörün adı",
    olustur: "Oluştur",
    yolYaz: "Yol yaz",
    yolEtiket: "Klasör yolu",
    yolGit: "Git",
    secilecek: "Seçilecek",
    sec: "Bu klasörü seç",
    klavye: "Oklarla gezinin, Enter ile açın, Backspace ile üst klasöre çıkın.",
  },
};
