// Projeler (Türkçe)
import { ilgi } from "../../yardimcilar/bicim";

export const projeler = {
  baslik: "Projeler",
  aciklama: "Her proje bir git deposu; kendi ekibi, panosu, hafızası ve denetim politikası olur",
  yeniProje: "Yeni proje",
  githubdanAc: "GitHub'dan aç",
  klasorBagla: "Klasör bağla",
  listeAlinamadi: "Proje listesi alınamadı.",
  acikProjeler: "Açık projeler",
  ekip: "Ekip",
  onay: "Onay",
  bugun: "Bugün",
  bugunBaslik: "Bugün işlenen token",
  karargahaGit: "Karargâha git",
  listedenCikar: "Listeden çıkar",
  cikarEtiket: (ad: string) => `${ad} projesini listeden çıkar`,
  cikarOnay: (ad: string) =>
    `${ad} ArnOrg listesinden çıkarılır. Repo ve .arnorg/ klasörü diskte kalır; aynı yolu yeniden bağlayabilirsiniz.`,
  cikarildi: (ad: string) => `${ad} listeden çıkarıldı. Dosyalara dokunulmadı.`,
  form: {
    ilkBaslik: "İlk projenizi açın",
    baslik: "Proje aç",
    kapat: "Formu kapat",
    /** Açıklama iki parça: arasında <code>.arnorg/</code> durur */
    ilkAciklamaOnce: "Proje, ArnOrg'un yönettiği bir git deposudur. Açtığınızda depoya ",
    ilkAciklamaSonra:
      " iskeleti (vizyon ve mimari notları, ekip kimlikleri, hafıza) eklenir ve bir CEO ajanı işe alınır. Siz brief verirsiniz; CEO planı çıkarır, ekibi önerir, işi dağıtır.",
  },
  ayar: {
    ac: "Proje ayarları",
    acEtiket: (ad: string) => `${ilgi(ad)} ayarları`,
    dal: "Çalışma dalı",
    dalIpucu: "Ekip bu dalda birlikte çalışır; ArnOrg her görevi buraya commit'ler.",
    dalDegistir: "Dalı değiştir",
    dalDegisti: (dal: string) => `Çalışma dalı ${dal} oldu.`,
    dallarAlinamadi: "Dallar alınamadı",
    dalFarkli: (mevcut: string, calisma: string) => `Ana repo şu an ${mevcut} dalında; çalışma dalı ${calisma}.`,
    uzak: "Uzak depo",
    uzakYok: "Bu projenin uzak deposu yok.",
    esitle: "Şimdi eşitle",
    gonder: "Şimdi gönder",
    bekleyen: (n: number) => `${n} commit gönderilmeyi bekliyor.`,
    sonEsitleme: (zaman: string) => `Son eşitleme ${zaman}`,
    githubAc: "GitHub'da depo aç",
    githubAcIpucu: "Depo açılır, çalışma dalı gönderilir ve origin olarak bağlanır.",
    githubAcildi: (depo: string) => `GitHub deposu açıldı: ${depo}.`,
    githubBagliDegil: "GitHub bağlı değil; depo açmak için önce bağlayın.",
    githubBagla: "Ayarlar'da bağla",
    gonderim: "Gönderim",
    otomatikGonder: "Görev kayıtlarından sonra uzak depoya gönder",
    otomatikGonderIpucu: "Kapalıyken görev kayıtları yalnız bu bilgisayardaki çalışma dalında kalır.",
    otomatikGonderUzakYok: "Uzak depo bağlanınca geçerli olur.",
    otomatikAcik: "Görev kayıtları uzak depoya da gönderilecek.",
    otomatikKapali: "Görev kayıtları yalnız bu bilgisayarda kalacak.",
  },
};
