// Tarayıcı ekranı: uygulama içi tarayıcı, öğe seçerek düzeltme notu, notlar paneli (Türkçe)
export const tarayici = {
  baslik: "Tarayıcı",
  bolumEtiketi: "Uygulama içi tarayıcı",
  arac: {
    etiket: "Tarayıcı araç çubuğu",
    geri: "Geri",
    ileri: "İleri",
    yenile: "Yenile",
    durdur: "Durdur",
    adres: "Adres",
    adresIpucu: "Adres yazın ya da arayın",
    adresBaslik: (kisayol: string) => `Adres ya da arama (${kisayol})`,
    git: "Git",
    sec: "Öğe seç",
    secBaslik: (kisayol: string) => `Sayfada bir öğeye tıklayıp not bırakın (${kisayol}) · Esc çıkar`,
    genislik: "Görünüm genişliği",
    masaustu: "Masaüstü",
    tablet: "Tablet 768",
    telefon: "Telefon 390",
  },
  /** Seçici açıkken sayfanın üstünde görünen kısa yönerge */
  secimIpucu: "Öğe seç · olmamış yere tıklayın · Esc çıkar",
  yukleniyor: "Sayfa yükleniyor",
  kare: "Sayfanın anlık görüntüsü",
  boyut: (genislik: number, yukseklik: number) => `${genislik} × ${yukseklik}`,
  yonerge: {
    baslik: "Projenin çalışan sayfasını açın",
    adim1: "Linkler'den birine tıklayın ya da adres çubuğuna sayfanın adresini yazın; ör. localhost:5173.",
    adim2: "Öğe seç'e basın ve sayfada olmamış yere tıklayın.",
    adim3: "Ne olmadığını yazın. Notlar yanda birikir; Hepsini yaptır hepsini CEO'ya iş olarak gönderir.",
    kisayollar: (adres: string, sec: string) => `${adres} adres · ${sec} öğe seç · Esc seçiciden çık`,
    hizli: "Yerel adresler",
    /** Projenin Linkleri (CEO'nun ve çalışanların bildirdiği, kurulun eklediği) */
    linkler: "Projenin linkleri",
  },
  hata: {
    baslik: "Sayfa açılamadı",
    ipucu: "Sunucu çalışıyor mu? Adresi denetleyip yeniden deneyin.",
  },
  web: {
    baslik: "Uygulama içi tarayıcı masaüstü uygulamasında çalışır",
    metin:
      "Masaüstü uygulamasında sayfa burada açılır; bir öğeye tıklayıp notunuzu bırakırsınız, seçici, öğe metni ve ekran görüntüsü nota kendiliğinden eklenir. Burada notu elle ekleyin: sayfanın adresi ve ne olmadığı yeterli.",
    formBaslik: "Elle not",
    adres: "Sayfanın adresi",
    adresIpucu: "localhost:5173/sepet",
    adresHata: "Geçerli bir adres yazın; ör. localhost:5173/sepet ya da https://ornek.com.",
    not: "Not",
    ekle: "Notu ekle",
  },
  not: {
    baslik: "Düzeltme notu",
    etiket: "Ne olmamış?",
    ipucu: "Burası olmamış: …",
    secici: "Seçici",
    metin: "Öğe metni",
    sayfa: "Sayfa",
    gorunum: "Görünüm",
    gorselAlt: "Seçilen öğenin ekran görüntüsü",
    gorselYok: "Ekran görüntüsü alınamadı; seçici ve öğe metni yine nota eklenir.",
    kaydet: "Kaydet",
    kaydetVeSec: "Kaydet, yenisini seç",
    kisayol: (kaydet: string) => `${kaydet} kaydeder · Esc vazgeçer`,
  },
  panel: {
    baslik: "Notlar",
    sayac: (n: number) => `${n} açık`,
    ac: "Notları göster",
    kapat: "Notları gizle",
    bosBaslik: "Henüz not yok",
    bosMasaustu: "Öğe seç'e basın, sayfada bir öğeye tıklayın ve ne olmadığını yazın.",
    bosWeb: "Formla sayfanın adresini ve notunuzu ekleyin; notlar burada birikir.",
    elle: "Elle eklendi",
    sayfayaGit: (adres: string) => `${adres} adresini aç`,
    duzenle: "Notu düzenle",
    sil: "Notu sil",
    silOnay: "Bu not silinsin mi? Ekran görüntüsü de silinir.",
    silOnayGonderilmis: "Bu not listeden silinsin mi? CEO'ya giden ekran görüntüsü yerinde kalır.",
    hepsiniYaptir: "Hepsini yaptır",
    hepsiniYaptirAlt: "Açık notlar tek mesajla CEO'ya gider; CEO her biri için görev açar ve atar.",
    gonderOnay: (n: number) => `${n} not CEO'ya gidecek. CEO her biri için kabul ölçütlü bir görev açıp uygun çalışana atayacak. Gönderilsin mi?`,
    gonder: "Gönder",
    gonderildi: (n: number) => `${n} not CEO'ya gitti.`,
    karargahIpucu: "CEO'nun yanıtı ve açtığı görevler Karargâh'ta görünür.",
    karargahaGec: "Karargâh'a geç",
    gonderilenler: (n: number) => `Gönderildi · ${n}`,
    gonderimZamani: (zaman: string) => `${zaman} gönderildi`,
  },
};
